# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RamsesGui.ui'
#
# Created: Tue Nov 22 17:48:23 2016
#      by: PyQt4 UI code generator 4.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(869, 603)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("result.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.QuickView = QtGui.QPushButton(self.centralwidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(185, 255, 202))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 255, 228))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(92, 127, 101))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(123, 170, 135))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(185, 255, 202))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 255, 228))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(185, 255, 202))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 255, 228))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(92, 127, 101))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(123, 170, 135))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(185, 255, 202))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 255, 228))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(92, 127, 101))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(185, 255, 202))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 255, 228))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(92, 127, 101))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(123, 170, 135))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(92, 127, 101))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(92, 127, 101))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(185, 255, 202))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(185, 255, 202))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(185, 255, 202))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.QuickView.setPalette(palette)
        self.QuickView.setObjectName(_fromUtf8("QuickView"))
        self.gridLayout.addWidget(self.QuickView, 0, 4, 1, 1)
        self.EditPhy = QtGui.QPushButton(self.centralwidget)
        self.EditPhy.setObjectName(_fromUtf8("EditPhy"))
        self.gridLayout.addWidget(self.EditPhy, 1, 0, 1, 1)
        self.Physical = QtGui.QLabel(self.centralwidget)
        self.Physical.setObjectName(_fromUtf8("Physical"))
        self.gridLayout.addWidget(self.Physical, 1, 1, 1, 1)
        self.Namelist = QtGui.QLabel(self.centralwidget)
        self.Namelist.setObjectName(_fromUtf8("Namelist"))
        self.gridLayout.addWidget(self.Namelist, 1, 2, 1, 1)
        self.NamefileInput = QtGui.QLineEdit(self.centralwidget)
        self.NamefileInput.setObjectName(_fromUtf8("NamefileInput"))
        self.gridLayout.addWidget(self.NamefileInput, 1, 3, 1, 1)
        self.ChooseNameFile = QtGui.QPushButton(self.centralwidget)
        self.ChooseNameFile.setObjectName(_fromUtf8("ChooseNameFile"))
        self.gridLayout.addWidget(self.ChooseNameFile, 1, 4, 1, 1)
        self.EditAMR = QtGui.QPushButton(self.centralwidget)
        self.EditAMR.setObjectName(_fromUtf8("EditAMR"))
        self.gridLayout.addWidget(self.EditAMR, 2, 0, 1, 1)
        self.AMR = QtGui.QLabel(self.centralwidget)
        self.AMR.setObjectName(_fromUtf8("AMR"))
        self.gridLayout.addWidget(self.AMR, 2, 1, 1, 1)
        self.Bin = QtGui.QLabel(self.centralwidget)
        self.Bin.setObjectName(_fromUtf8("Bin"))
        self.gridLayout.addWidget(self.Bin, 2, 2, 1, 1)
        self.BinFileInput = QtGui.QLineEdit(self.centralwidget)
        self.BinFileInput.setObjectName(_fromUtf8("BinFileInput"))
        self.gridLayout.addWidget(self.BinFileInput, 2, 3, 1, 1)
        self.ChooseFileBin = QtGui.QPushButton(self.centralwidget)
        self.ChooseFileBin.setObjectName(_fromUtf8("ChooseFileBin"))
        self.gridLayout.addWidget(self.ChooseFileBin, 2, 4, 1, 1)
        self.EditRun_2 = QtGui.QPushButton(self.centralwidget)
        self.EditRun_2.setObjectName(_fromUtf8("EditRun_2"))
        self.gridLayout.addWidget(self.EditRun_2, 3, 0, 1, 1)
        self.Run = QtGui.QLabel(self.centralwidget)
        self.Run.setObjectName(_fromUtf8("Run"))
        self.gridLayout.addWidget(self.Run, 3, 1, 1, 1)
        self.EditOut = QtGui.QPushButton(self.centralwidget)
        self.EditOut.setObjectName(_fromUtf8("EditOut"))
        self.gridLayout.addWidget(self.EditOut, 4, 0, 1, 1)
        self.Output = QtGui.QLabel(self.centralwidget)
        self.Output.setObjectName(_fromUtf8("Output"))
        self.gridLayout.addWidget(self.Output, 4, 1, 1, 1)
        self.EditInit = QtGui.QPushButton(self.centralwidget)
        self.EditInit.setObjectName(_fromUtf8("EditInit"))
        self.gridLayout.addWidget(self.EditInit, 5, 0, 1, 1)
        self.Initial = QtGui.QLabel(self.centralwidget)
        self.Initial.setObjectName(_fromUtf8("Initial"))
        self.gridLayout.addWidget(self.Initial, 5, 1, 1, 1)
        self.EditRefine = QtGui.QPushButton(self.centralwidget)
        self.EditRefine.setObjectName(_fromUtf8("EditRefine"))
        self.gridLayout.addWidget(self.EditRefine, 6, 0, 1, 1)
        self.Refinement = QtGui.QLabel(self.centralwidget)
        self.Refinement.setObjectName(_fromUtf8("Refinement"))
        self.gridLayout.addWidget(self.Refinement, 6, 1, 1, 1)
        self.EditBound = QtGui.QPushButton(self.centralwidget)
        self.EditBound.setObjectName(_fromUtf8("EditBound"))
        self.gridLayout.addWidget(self.EditBound, 7, 0, 1, 1)
        self.Boundary = QtGui.QLabel(self.centralwidget)
        self.Boundary.setObjectName(_fromUtf8("Boundary"))
        self.gridLayout.addWidget(self.Boundary, 7, 1, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 869, 27))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionEdir = QtGui.QAction(MainWindow)
        self.actionEdir.setObjectName(_fromUtf8("actionEdir"))
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.menuFile.addAction(self.actionEdir)
        self.menuFile.addAction(self.actionQuit)
        self.menuFile.addAction(self.actionSave)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        MainWindow.setStatusTip(_translate("MainWindow", "Open AMRViewer", None))
        self.QuickView.setText(_translate("MainWindow", "Quick View", None))
        self.EditPhy.setStatusTip(_translate("MainWindow", "Edit Physical Parameters", None))
        self.EditPhy.setText(_translate("MainWindow", "Edit", None))
        self.Physical.setText(_translate("MainWindow", "Physical Parameters", None))
        self.Namelist.setText(_translate("MainWindow", "Namelist Didirectory", None))
        self.ChooseNameFile.setText(_translate("MainWindow", "File", None))
        self.EditAMR.setStatusTip(_translate("MainWindow", "Edit AMR Parameters", None))
        self.EditAMR.setText(_translate("MainWindow", "Edit", None))
        self.AMR.setText(_translate("MainWindow", "AMR Parameters", None))
        self.Bin.setText(_translate("MainWindow", "Ramses Bin ", None))
        self.ChooseFileBin.setText(_translate("MainWindow", "File", None))
        self.EditRun_2.setStatusTip(_translate("MainWindow", "Edit Run Parameters", None))
        self.EditRun_2.setText(_translate("MainWindow", "Edit", None))
        self.Run.setText(_translate("MainWindow", "Run Parameters", None))
        self.EditOut.setStatusTip(_translate("MainWindow", "Edit Output Parameters", None))
        self.EditOut.setText(_translate("MainWindow", "Edit", None))
        self.Output.setText(_translate("MainWindow", "Output Parameters", None))
        self.EditInit.setStatusTip(_translate("MainWindow", "Edit Initial Conditions", None))
        self.EditInit.setText(_translate("MainWindow", "Edit", None))
        self.Initial.setText(_translate("MainWindow", "Initial Condition Parameters", None))
        self.EditRefine.setStatusTip(_translate("MainWindow", "Edit Refinement Parameters", None))
        self.EditRefine.setText(_translate("MainWindow", "Edit", None))
        self.Refinement.setText(_translate("MainWindow", "Refinement Parameters", None))
        self.EditBound.setStatusTip(_translate("MainWindow", "Edit Bounday Parameters", None))
        self.EditBound.setText(_translate("MainWindow", "Edit", None))
        self.Boundary.setText(_translate("MainWindow", "Bounday Condition Parameters", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.actionEdir.setText(_translate("MainWindow", "Edir", None))
        self.actionQuit.setText(_translate("MainWindow", "Quit", None))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q", None))
        self.actionSave.setText(_translate("MainWindow", "Save", None))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

