import sys
from PyQt4 import QtCore, QtGui
try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)





class Phy_Frame(object):
    def setupUi(self, cosmo):
        cosmo.setObjectName(_fromUtf8("cosmo"))
        cosmo.resize(833, 559)
        cosmo.setFrameShape(QtGui.QFrame.StyledPanel)
        cosmo.setFrameShadow(QtGui.QFrame.Raised)
       
        self.Save = QtGui.QPushButton(cosmo)
        self.Save.setGeometry(QtCore.QRect(0, 0, 85, 27))
        self.Save.setObjectName(_fromUtf8("Save"))
        self.Reset = QtGui.QPushButton(cosmo)
        self.Reset.setGeometry(QtCore.QRect(90, 0, 85, 27))
        self.Reset.setObjectName(_fromUtf8("Reset"))


        self.gridLayout = QtGui.QGridLayout(cosmo)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.cooling = QtGui.QLabel(cosmo)
        self.cooling.setStatusTip(_fromUtf8(""))
        self.cooling.setObjectName(_fromUtf8("cooling"))
        self.gridLayout.addWidget(self.cooling, 0, 0, 1, 1)
        self.editcooling = QtGui.QLineEdit(cosmo)
        self.editcooling.setObjectName(_fromUtf8("editcooling"))
        self.gridLayout.addWidget(self.editcooling, 0, 1, 1, 1)
        self.a_spec = QtGui.QLabel(cosmo)
        self.a_spec.setObjectName(_fromUtf8("a_spec"))
        self.gridLayout.addWidget(self.a_spec, 0, 2, 1, 1)
        self.edita_spec = QtGui.QLineEdit(cosmo)
        self.edita_spec.setObjectName(_fromUtf8("edita_spec"))
        self.gridLayout.addWidget(self.edita_spec, 0, 3, 1, 1)
        self.n_star = QtGui.QLabel(cosmo)
        self.n_star.setObjectName(_fromUtf8("n_star"))
        self.gridLayout.addWidget(self.n_star, 0, 4, 1, 1)
        self.editn_star = QtGui.QLineEdit(cosmo)
        self.editn_star.setObjectName(_fromUtf8("editn_star"))
        self.gridLayout.addWidget(self.editn_star, 0, 5, 1, 1)
        self.isothermal = QtGui.QLabel(cosmo)
        self.isothermal.setObjectName(_fromUtf8("isothermal"))
        self.gridLayout.addWidget(self.isothermal, 1, 0, 1, 1)
        self.editisothermal = QtGui.QLineEdit(cosmo)
        self.editisothermal.setObjectName(_fromUtf8("editisothermal"))
        self.gridLayout.addWidget(self.editisothermal, 1, 1, 1, 1)
        self.z_reion = QtGui.QLabel(cosmo)
        self.z_reion.setObjectName(_fromUtf8("z_reion"))
        self.gridLayout.addWidget(self.z_reion, 1, 2, 1, 1)
        self.editreion = QtGui.QLineEdit(cosmo)
        self.editreion.setObjectName(_fromUtf8("editreion"))
        self.gridLayout.addWidget(self.editreion, 1, 3, 1, 1)
        self.del_star = QtGui.QLabel(cosmo)
        self.del_star.setObjectName(_fromUtf8("del_star"))
        self.gridLayout.addWidget(self.del_star, 1, 4, 1, 1)
        self.editdel_star = QtGui.QLineEdit(cosmo)
        self.editdel_star.setObjectName(_fromUtf8("editdel_star"))
        self.gridLayout.addWidget(self.editdel_star, 1, 5, 1, 1)
        self.metal = QtGui.QLabel(cosmo)
        self.metal.setStatusTip(_fromUtf8(""))
        self.metal.setObjectName(_fromUtf8("metal"))
        self.gridLayout.addWidget(self.metal, 2, 0, 1, 1)
        self.editmetal = QtGui.QLineEdit(cosmo)
        self.editmetal.setObjectName(_fromUtf8("editmetal"))
        self.gridLayout.addWidget(self.editmetal, 2, 1, 1, 1)
        self.z_ave = QtGui.QLabel(cosmo)
        self.z_ave.setObjectName(_fromUtf8("z_ave"))
        self.gridLayout.addWidget(self.z_ave, 2, 2, 1, 1)
        self.editz_ave = QtGui.QLineEdit(cosmo)
        self.editz_ave.setObjectName(_fromUtf8("editz_ave"))
        self.gridLayout.addWidget(self.editz_ave, 2, 3, 1, 1)
        self.T2_star = QtGui.QLabel(cosmo)
        self.T2_star.setObjectName(_fromUtf8("T2_star"))
        self.gridLayout.addWidget(self.T2_star, 2, 4, 1, 1)
        self.editT2_star = QtGui.QLineEdit(cosmo)
        self.editT2_star.setObjectName(_fromUtf8("editT2_star"))
        self.gridLayout.addWidget(self.editT2_star, 2, 5, 1, 1)
        self.haardt_madau = QtGui.QLabel(cosmo)
        self.haardt_madau.setObjectName(_fromUtf8("haardt_madau"))
        self.gridLayout.addWidget(self.haardt_madau, 3, 0, 1, 1)
        self.edithaardt_madau = QtGui.QLineEdit(cosmo)
        self.edithaardt_madau.setObjectName(_fromUtf8("edithaardt_madau"))
        self.gridLayout.addWidget(self.edithaardt_madau, 3, 1, 1, 1)
        self.t_star = QtGui.QLabel(cosmo)
        self.t_star.setObjectName(_fromUtf8("t_star"))
        self.gridLayout.addWidget(self.t_star, 3, 2, 1, 1)
        self.editt_star = QtGui.QLineEdit(cosmo)
        self.editt_star.setObjectName(_fromUtf8("editt_star"))
        self.gridLayout.addWidget(self.editt_star, 3, 3, 1, 1)
        self.g_star = QtGui.QLabel(cosmo)
        self.g_star.setObjectName(_fromUtf8("g_star"))
        self.gridLayout.addWidget(self.g_star, 3, 4, 1, 1)
        self.editg_star = QtGui.QLineEdit(cosmo)
        self.editg_star.setObjectName(_fromUtf8("editg_star"))
        self.gridLayout.addWidget(self.editg_star, 3, 5, 1, 1)
        self.J21 = QtGui.QLabel(cosmo)
        self.J21.setObjectName(_fromUtf8("J21"))
        self.gridLayout.addWidget(self.J21, 4, 0, 1, 1)
        self.editJ21 = QtGui.QLineEdit(cosmo)
        self.editJ21.setObjectName(_fromUtf8("editJ21"))
        self.gridLayout.addWidget(self.editJ21, 4, 1, 1, 1)
        self.eps_star = QtGui.QLabel(cosmo)
        self.eps_star.setObjectName(_fromUtf8("eps_star"))
        self.gridLayout.addWidget(self.eps_star, 4, 2, 1, 1)
        self.editeps_star = QtGui.QLineEdit(cosmo)
        self.editeps_star.setObjectName(_fromUtf8("editeps_star"))
        self.gridLayout.addWidget(self.editeps_star, 4, 3, 1, 1)
        self.eta_sn = QtGui.QLabel(cosmo)
        self.eta_sn.setObjectName(_fromUtf8("eta_sn"))
        self.gridLayout.addWidget(self.eta_sn, 4, 4, 1, 1)
        self.editeta_sn = QtGui.QLineEdit(cosmo)
        self.editeta_sn.setObjectName(_fromUtf8("editeta_sn"))
        self.gridLayout.addWidget(self.editeta_sn, 4, 5, 1, 1)
        self.ndebris = QtGui.QLabel(cosmo)
        self.ndebris.setObjectName(_fromUtf8("ndebris"))
        self.gridLayout.addWidget(self.ndebris, 5, 0, 1, 1)
        self.editndebris = QtGui.QLineEdit(cosmo)
        self.editndebris.setObjectName(_fromUtf8("editndebris"))
        self.gridLayout.addWidget(self.editndebris, 5, 1, 1, 1)
        self.f_w = QtGui.QLabel(cosmo)
        self.f_w.setObjectName(_fromUtf8("f_w"))
        self.gridLayout.addWidget(self.f_w, 5, 2, 1, 1)
        self.editf_w = QtGui.QLineEdit(cosmo)
        self.editf_w.setObjectName(_fromUtf8("editf_w"))
        self.gridLayout.addWidget(self.editf_w, 5, 3, 1, 1)
        self.yld = QtGui.QLabel(cosmo)
        self.yld.setObjectName(_fromUtf8("yield"))
        self.gridLayout.addWidget(self.yld, 5, 4, 1, 1)
        self.edityield = QtGui.QLineEdit(cosmo)
        self.edityield.setObjectName(_fromUtf8("edityield"))
        self.gridLayout.addWidget(self.edityield, 5, 5, 1, 1)
        self.label_4 = QtGui.QLabel(cosmo)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 6, 0, 1, 1)
        self.editf_ek = QtGui.QLineEdit(cosmo)
        self.editf_ek.setObjectName(_fromUtf8("editf_ek"))
        self.gridLayout.addWidget(self.editf_ek, 6, 1, 1, 1)
        self.r_bubble = QtGui.QLabel(cosmo)
        self.r_bubble.setStatusTip(_fromUtf8(""))
        self.r_bubble.setObjectName(_fromUtf8("r_bubble"))
        self.gridLayout.addWidget(self.r_bubble, 6, 2, 1, 1)
        self.editr_bubble = QtGui.QLineEdit(cosmo)
        self.editr_bubble.setObjectName(_fromUtf8("editr_bubble"))
        self.gridLayout.addWidget(self.editr_bubble, 6, 3, 1, 1)

        self.retranslateUi(cosmo)
        QtCore.QMetaObject.connectSlotsByName(cosmo)

    def retranslateUi(self, cosmo):
        cosmo.setWindowTitle(_translate("cosmo", "Frame", None))
        self.cooling.setText(_translate("cosmo", "cooling", None))
        self.editcooling.setStatusTip(_translate("cosmo", "edit cooling", None))
        self.a_spec.setText(_translate("cosmo", "a_spec", None))
        self.edita_spec.setStatusTip(_translate("cosmo", "edit a_spec", None))
        self.n_star.setText(_translate("cosmo", "n_star", None))
        self.editn_star.setStatusTip(_translate("cosmo", "edit n_star", None))
        self.isothermal.setText(_translate("cosmo", "isothermal", None))
        self.editisothermal.setStatusTip(_translate("cosmo", "edit isothermal", None))
        self.z_reion.setText(_translate("cosmo", "z_reion", None))
        self.editreion.setStatusTip(_translate("cosmo", "edit reion", None))
        self.del_star.setText(_translate("cosmo", "del_star", None))
        self.editdel_star.setStatusTip(_translate("cosmo", "edit del_star", None))
        self.metal.setText(_translate("cosmo", "metal", None))
        self.editmetal.setStatusTip(_translate("cosmo", "edit metal", None))
        self.z_ave.setText(_translate("cosmo", "z_ave", None))
        self.editz_ave.setStatusTip(_translate("cosmo", "edit z_ave", None))
        self.T2_star.setText(_translate("cosmo", "T2_star", None))
        self.editT2_star.setStatusTip(_translate("cosmo", "edit T2_star", None))
        self.haardt_madau.setText(_translate("cosmo", "haardt_madau", None))
        self.edithaardt_madau.setStatusTip(_translate("cosmo", "edit haardt_madau", None))
        self.t_star.setText(_translate("cosmo", "t_star ", None))
        self.editt_star.setStatusTip(_translate("cosmo", "edit t_star", None))
        self.g_star.setText(_translate("cosmo", "g_star", None))
        self.editg_star.setStatusTip(_translate("cosmo", "edit g_star", None))
        self.J21.setText(_translate("cosmo", "J21", None))
        self.editJ21.setStatusTip(_translate("cosmo", "edit J21", None))
        self.eps_star.setText(_translate("cosmo", "eps_star", None))
        self.editeps_star.setStatusTip(_translate("cosmo", "edit eps_star", None))
        self.eta_sn.setText(_translate("cosmo", "eta_sn", None))
        self.editeta_sn.setStatusTip(_translate("cosmo", "edit eta_sn", None))
        self.ndebris.setText(_translate("cosmo", "ndebris", None))
        self.editndebris.setStatusTip(_translate("cosmo", "edit ndebris", None))
        self.f_w.setText(_translate("cosmo", "f_w", None))
        self.editf_w.setStatusTip(_translate("cosmo", "edit f_w", None))
        self.yld.setText(_translate("cosmo", "yield", None))
        self.edityield.setStatusTip(_translate("cosmo", "edit yield", None))
        self.label_4.setText(_translate("cosmo", "f_ek\n"
"", None))
        self.editf_ek.setStatusTip(_translate("cosmo", "edit f_ek", None))
        self.r_bubble.setText(_translate("cosmo", "r_bubble", None))
        self.editr_bubble.setStatusTip(_translate("cosmo", "edit r_bubble", None))


        self.Save.setStatusTip(_translate("Frame", "Save variables", None))
        self.Save.setText(_translate("Frame", "Save", None))
        self.Reset.setStatusTip(_translate("Frame", "Reset value", None))
        self.Reset.setText(_translate("Frame", "Reset", None))



       

class AMR_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName(_fromUtf8("Frame"))
        Frame.resize(637, 206)
        Frame.setFrameShape(QtGui.QFrame.StyledPanel)
        Frame.setFrameShadow(QtGui.QFrame.Raised)

        self.Save = QtGui.QPushButton(Frame)
        self.Save.setGeometry(QtCore.QRect(0, 0, 85, 27))
        self.Save.setObjectName(_fromUtf8("Save"))
        self.Reset = QtGui.QPushButton(Frame)
        self.Reset.setGeometry(QtCore.QRect(90, 0, 85, 27))
        self.Reset.setObjectName(_fromUtf8("Reset"))

        self.gridLayout = QtGui.QGridLayout(Frame)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.levelmin = QtGui.QLabel(Frame)
        self.levelmin.setStatusTip(_fromUtf8(""))
        self.levelmin.setObjectName(_fromUtf8("levelmin"))
        self.gridLayout.addWidget(self.levelmin, 0, 0, 1, 1)
        self.editlevelmin = QtGui.QLineEdit(Frame)
        self.editlevelmin.setObjectName(_fromUtf8("editlevelmin"))
        self.gridLayout.addWidget(self.editlevelmin, 0, 1, 1, 1)
        self.hm = QtGui.QLabel(Frame)
        self.hm.setObjectName(_fromUtf8("hm"))
        self.gridLayout.addWidget(self.hm, 0, 2, 1, 1)
        self.editngridtot = QtGui.QLineEdit(Frame)
        self.editngridtot.setObjectName(_fromUtf8("editngridtot"))
        self.gridLayout.addWidget(self.editngridtot, 0, 3, 1, 1)
        self.levelmax = QtGui.QLabel(Frame)
        self.levelmax.setObjectName(_fromUtf8("levelmax"))
        self.gridLayout.addWidget(self.levelmax, 1, 0, 1, 1)
        self.editlevelmax = QtGui.QLineEdit(Frame)
        self.editlevelmax.setObjectName(_fromUtf8("editlevelmax"))
        self.gridLayout.addWidget(self.editlevelmax, 1, 1, 1, 1)
        self.npartmax = QtGui.QLabel(Frame)
        self.npartmax.setObjectName(_fromUtf8("npartmax"))
        self.gridLayout.addWidget(self.npartmax, 1, 2, 1, 1)
        self.editnpartmax = QtGui.QLineEdit(Frame)
        self.editnpartmax.setObjectName(_fromUtf8("editnpartmax"))
        self.gridLayout.addWidget(self.editnpartmax, 1, 3, 1, 1)
        self.ngridmax = QtGui.QLabel(Frame)
        self.ngridmax.setStatusTip(_fromUtf8(""))
        self.ngridmax.setObjectName(_fromUtf8("ngridmax"))
        self.gridLayout.addWidget(self.ngridmax, 2, 0, 1, 1)
        self.editngridmax = QtGui.QLineEdit(Frame)
        self.editngridmax.setObjectName(_fromUtf8("editngridmax"))
        self.gridLayout.addWidget(self.editngridmax, 2, 1, 1, 1)
        self.nparttot = QtGui.QLabel(Frame)
        self.nparttot.setObjectName(_fromUtf8("nparttot"))
        self.gridLayout.addWidget(self.nparttot, 2, 2, 1, 1)
        self.editnparttot = QtGui.QLineEdit(Frame)
        self.editnparttot.setObjectName(_fromUtf8("editnparttot"))
        self.gridLayout.addWidget(self.editnparttot, 2, 3, 1, 1)
        self.nexpand = QtGui.QLabel(Frame)
        self.nexpand.setObjectName(_fromUtf8("nexpand"))
        self.gridLayout.addWidget(self.nexpand, 3, 0, 1, 1)
        self.editnexpand = QtGui.QLineEdit(Frame)
        self.editnexpand.setObjectName(_fromUtf8("editnexpand"))
        self.gridLayout.addWidget(self.editnexpand, 3, 1, 1, 1)
        self.boxlen = QtGui.QLabel(Frame)
        self.boxlen.setObjectName(_fromUtf8("boxlen"))
        self.gridLayout.addWidget(self.boxlen, 3, 2, 1, 1)
        self.editboxlen = QtGui.QLineEdit(Frame)
        self.editboxlen.setObjectName(_fromUtf8("editboxlen"))
        self.gridLayout.addWidget(self.editboxlen, 3, 3, 1, 1)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        Frame.setWindowTitle(_translate("Frame", "Frame", None))
        self.levelmin.setText(_translate("Frame", "levelmin", None))
        self.editlevelmin.setStatusTip(_translate("Frame", "edit levelmax", None))
        self.hm.setText(_translate("Frame", "ngridtot", None))
        self.editngridtot.setStatusTip(_translate("Frame", "edit ngridtot", None))
        self.levelmax.setText(_translate("Frame", "levelmax", None))
        self.editlevelmax.setStatusTip(_translate("Frame", "edit levelmax", None))
        self.npartmax.setText(_translate("Frame", "npartmax", None))
        self.editnpartmax.setStatusTip(_translate("Frame", "edit npartmax", None))
        self.ngridmax.setText(_translate("Frame", "ngridmax", None))
        self.editngridmax.setStatusTip(_translate("Frame", "edit ngridmax", None))
        self.nparttot.setText(_translate("Frame", "nparttot", None))
        self.editnparttot.setStatusTip(_translate("Frame", "edit nparttot", None))
        self.nexpand.setText(_translate("Frame", "nexpand", None))
        self.editnexpand.setStatusTip(_translate("Frame", "edit nexpand", None))
        self.boxlen.setText(_translate("Frame", "boxlen", None))
        self.editboxlen.setStatusTip(_translate("Frame", "edit boxlen", None))

        self.Save.setStatusTip(_translate("Frame", "Save variables", None))
        self.Save.setText(_translate("Frame", "Save", None))
        self.Reset.setStatusTip(_translate("Frame", "Reset value", None))
        self.Reset.setText(_translate("Frame", "Reset", None))





class Init_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName(_fromUtf8("Frame"))
        Frame.resize(561, 571)
        Frame.setFrameShape(QtGui.QFrame.StyledPanel)
        Frame.setFrameShadow(QtGui.QFrame.Raised)

        self.Save = QtGui.QPushButton(Frame)
        self.Save.setGeometry(QtCore.QRect(0, 0, 85, 27))
        self.Save.setObjectName(_fromUtf8("Save"))
        self.Reset = QtGui.QPushButton(Frame)
        self.Reset.setGeometry(QtCore.QRect(90, 0, 85, 27))
        self.Reset.setObjectName(_fromUtf8("Reset"))


        self.gridLayout = QtGui.QGridLayout(Frame)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.nregion = QtGui.QLabel(Frame)
        self.nregion.setStatusTip(_fromUtf8(""))
        self.nregion.setObjectName(_fromUtf8("nregion"))
        self.gridLayout.addWidget(self.nregion, 0, 0, 1, 1)
        self.editnregion = QtGui.QLineEdit(Frame)
        self.editnregion.setObjectName(_fromUtf8("editnregion"))
        self.gridLayout.addWidget(self.editnregion, 0, 1, 1, 1)
        self.length_x = QtGui.QLabel(Frame)
        self.length_x.setObjectName(_fromUtf8("length_x"))
        self.gridLayout.addWidget(self.length_x, 0, 2, 1, 1)
        self.editlength_x = QtGui.QLineEdit(Frame)
        self.editlength_x.setObjectName(_fromUtf8("editlength_x"))
        self.gridLayout.addWidget(self.editlength_x, 0, 3, 1, 1)
        self.region_type = QtGui.QLabel(Frame)
        self.region_type.setObjectName(_fromUtf8("region_type"))
        self.gridLayout.addWidget(self.region_type, 1, 0, 1, 1)
        self.editregion_type = QtGui.QLineEdit(Frame)
        self.editregion_type.setObjectName(_fromUtf8("editregion_type"))
        self.gridLayout.addWidget(self.editregion_type, 1, 1, 1, 1)
        self.nparttot = QtGui.QLabel(Frame)
        self.nparttot.setObjectName(_fromUtf8("nparttot"))
        self.gridLayout.addWidget(self.nparttot, 1, 2, 1, 1)
        self.editlength_y = QtGui.QLineEdit(Frame)
        self.editlength_y.setObjectName(_fromUtf8("editlength_y"))
        self.gridLayout.addWidget(self.editlength_y, 1, 3, 1, 1)
        self.x_center = QtGui.QLabel(Frame)
        self.x_center.setStatusTip(_fromUtf8(""))
        self.x_center.setObjectName(_fromUtf8("x_center"))
        self.gridLayout.addWidget(self.x_center, 2, 0, 1, 1)
        self.editx_center = QtGui.QLineEdit(Frame)
        self.editx_center.setObjectName(_fromUtf8("editx_center"))
        self.gridLayout.addWidget(self.editx_center, 2, 1, 1, 1)
        self.length_z = QtGui.QLabel(Frame)
        self.length_z.setObjectName(_fromUtf8("length_z"))
        self.gridLayout.addWidget(self.length_z, 2, 2, 1, 1)
        self.editlength_z = QtGui.QLineEdit(Frame)
        self.editlength_z.setObjectName(_fromUtf8("editlength_z"))
        self.gridLayout.addWidget(self.editlength_z, 2, 3, 1, 1)
        self.y_center = QtGui.QLabel(Frame)
        self.y_center.setObjectName(_fromUtf8("y_center"))
        self.gridLayout.addWidget(self.y_center, 3, 0, 1, 1)
        self.edity_center = QtGui.QLineEdit(Frame)
        self.edity_center.setObjectName(_fromUtf8("edity_center"))
        self.gridLayout.addWidget(self.edity_center, 3, 1, 1, 1)
        self.exp_region = QtGui.QLabel(Frame)
        self.exp_region.setObjectName(_fromUtf8("exp_region"))
        self.gridLayout.addWidget(self.exp_region, 3, 2, 1, 1)
        self.editexp_region = QtGui.QLineEdit(Frame)
        self.editexp_region.setObjectName(_fromUtf8("editexp_region"))
        self.gridLayout.addWidget(self.editexp_region, 3, 3, 1, 1)
        self.z_center = QtGui.QLabel(Frame)
        self.z_center.setObjectName(_fromUtf8("z_center"))
        self.gridLayout.addWidget(self.z_center, 4, 0, 1, 1)
        self.editz_center = QtGui.QLineEdit(Frame)
        self.editz_center.setObjectName(_fromUtf8("editz_center"))
        self.gridLayout.addWidget(self.editz_center, 4, 1, 1, 1)
        self.p_region_2 = QtGui.QLabel(Frame)
        self.p_region_2.setObjectName(_fromUtf8("p_region_2"))
        self.gridLayout.addWidget(self.p_region_2, 4, 2, 1, 1)
        self.editfiletype = QtGui.QLineEdit(Frame)
        self.editfiletype.setObjectName(_fromUtf8("editfiletype"))
        self.gridLayout.addWidget(self.editfiletype, 4, 3, 1, 1)
        self.d_region = QtGui.QLabel(Frame)
        self.d_region.setObjectName(_fromUtf8("d_region"))
        self.gridLayout.addWidget(self.d_region, 5, 0, 1, 1)
        self.editd_region = QtGui.QLineEdit(Frame)
        self.editd_region.setObjectName(_fromUtf8("editd_region"))
        self.gridLayout.addWidget(self.editd_region, 5, 1, 1, 1)
        self.aexp_ini = QtGui.QLabel(Frame)
        self.aexp_ini.setObjectName(_fromUtf8("aexp_ini"))
        self.gridLayout.addWidget(self.aexp_ini, 5, 2, 1, 1)
        self.editaexp_ini = QtGui.QLineEdit(Frame)
        self.editaexp_ini.setObjectName(_fromUtf8("editaexp_ini"))
        self.gridLayout.addWidget(self.editaexp_ini, 5, 3, 1, 1)
        self.u_region = QtGui.QLabel(Frame)
        self.u_region.setObjectName(_fromUtf8("u_region"))
        self.gridLayout.addWidget(self.u_region, 6, 0, 1, 1)
        self.editu_region = QtGui.QLineEdit(Frame)
        self.editu_region.setObjectName(_fromUtf8("editu_region"))
        self.gridLayout.addWidget(self.editu_region, 6, 1, 1, 1)
        self.multiple = QtGui.QLabel(Frame)
        self.multiple.setObjectName(_fromUtf8("multiple"))
        self.gridLayout.addWidget(self.multiple, 6, 2, 1, 1)
        self.editmultiple = QtGui.QLineEdit(Frame)
        self.editmultiple.setObjectName(_fromUtf8("editmultiple"))
        self.gridLayout.addWidget(self.editmultiple, 6, 3, 1, 1)
        self.w_region = QtGui.QLabel(Frame)
        self.w_region.setObjectName(_fromUtf8("w_region"))
        self.gridLayout.addWidget(self.w_region, 7, 0, 1, 1)
        self.editw_region = QtGui.QLineEdit(Frame)
        self.editw_region.setObjectName(_fromUtf8("editw_region"))
        self.gridLayout.addWidget(self.editw_region, 7, 1, 1, 1)
        self.initfile = QtGui.QLabel(Frame)
        self.initfile.setObjectName(_fromUtf8("initfile"))
        self.gridLayout.addWidget(self.initfile, 7, 2, 1, 1)
        self.editinitfile = QtGui.QLineEdit(Frame)
        self.editinitfile.setObjectName(_fromUtf8("editinitfile"))
        self.gridLayout.addWidget(self.editinitfile, 7, 3, 1, 1)
        self.p_region = QtGui.QLabel(Frame)
        self.p_region.setObjectName(_fromUtf8("p_region"))
        self.gridLayout.addWidget(self.p_region, 8, 0, 1, 1)
        self.editp_region = QtGui.QLineEdit(Frame)
        self.editp_region.setObjectName(_fromUtf8("editp_region"))
        self.gridLayout.addWidget(self.editp_region, 8, 1, 1, 1)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        Frame.setWindowTitle(_translate("Frame", "Frame", None))
        self.nregion.setText(_translate("Frame", "nregion", None))
        self.editnregion.setStatusTip(_translate("Frame", "edit nregion", None))
        self.length_x.setText(_translate("Frame", "length_x", None))
        self.editlength_x.setStatusTip(_translate("Frame", "edit length_x", None))
        self.region_type.setText(_translate("Frame", "region_type", None))
        self.editregion_type.setStatusTip(_translate("Frame", "edit region_type", None))
        self.nparttot.setText(_translate("Frame", "length_y", None))
        self.editlength_y.setStatusTip(_translate("Frame", "edit length_y", None))
        self.x_center.setText(_translate("Frame", "x_center", None))
        self.editx_center.setStatusTip(_translate("Frame", "edit x_center", None))
        self.length_z.setText(_translate("Frame", "length_z", None))
        self.editlength_z.setStatusTip(_translate("Frame", "edit length_z", None))
        self.y_center.setText(_translate("Frame", "y_center", None))
        self.edity_center.setStatusTip(_translate("Frame", "edit y_center", None))
        self.exp_region.setText(_translate("Frame", "exp_region", None))
        self.editexp_region.setStatusTip(_translate("Frame", "edit exp_region", None))
        self.z_center.setText(_translate("Frame", "z_center", None))
        self.editz_center.setStatusTip(_translate("Frame", "edit z_center", None))
        self.p_region_2.setText(_translate("Frame", "filetype", None))
        self.editfiletype.setStatusTip(_translate("Frame", "edit filetype", None))
        self.d_region.setText(_translate("Frame", "d_region", None))
        self.editd_region.setStatusTip(_translate("Frame", "edit d_region", None))
        self.aexp_ini.setText(_translate("Frame", "aexp_ini", None))
        self.editaexp_ini.setStatusTip(_translate("Frame", "edit aexp_ini", None))
        self.u_region.setText(_translate("Frame", "u_region", None))
        self.editu_region.setStatusTip(_translate("Frame", "edit u_region", None))
        self.multiple.setText(_translate("Frame", "multiple", None))
        self.editmultiple.setStatusTip(_translate("Frame", "edit multiple", None))
        self.w_region.setText(_translate("Frame", "w_region", None))
        self.editw_region.setStatusTip(_translate("Frame", "edit w_region", None))
        self.initfile.setText(_translate("Frame", "initfile", None))
        self.editinitfile.setStatusTip(_translate("Frame", "edit initfile", None))
        self.p_region.setText(_translate("Frame", "p_region", None))
        self.editp_region.setStatusTip(_translate("Frame", "edit p_region", None))

        self.Save.setStatusTip(_translate("Frame", "Save variables", None))
        self.Save.setText(_translate("Frame", "Save", None))
        self.Reset.setStatusTip(_translate("Frame", "Reset value", None))
        self.Reset.setText(_translate("Frame", "Reset", None))






class Output_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName(_fromUtf8("Frame"))
        Frame.resize(625, 341)
        Frame.setFrameShape(QtGui.QFrame.StyledPanel)
        Frame.setFrameShadow(QtGui.QFrame.Raised)
        
        self.Save = QtGui.QPushButton(Frame)
        self.Save.setGeometry(QtCore.QRect(0, 0, 85, 27))
        self.Save.setObjectName(_fromUtf8("Save"))
        self.Reset = QtGui.QPushButton(Frame)
        self.Reset.setGeometry(QtCore.QRect(90, 0, 85, 27))
        self.Reset.setObjectName(_fromUtf8("Reset"))


        self.gridLayout = QtGui.QGridLayout(Frame)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tend = QtGui.QLabel(Frame)
        self.tend.setStatusTip(_fromUtf8(""))
        self.tend.setObjectName(_fromUtf8("tend"))
        self.gridLayout.addWidget(self.tend, 0, 0, 1, 1)
        self.edittend = QtGui.QLineEdit(Frame)
        self.edittend.setObjectName(_fromUtf8("edittend"))
        self.gridLayout.addWidget(self.edittend, 0, 1, 1, 1)
        self.noutput = QtGui.QLabel(Frame)
        self.noutput.setObjectName(_fromUtf8("noutput"))
        self.gridLayout.addWidget(self.noutput, 0, 2, 1, 1)
        self.editnoutput = QtGui.QLineEdit(Frame)
        self.editnoutput.setObjectName(_fromUtf8("editnoutput"))
        self.gridLayout.addWidget(self.editnoutput, 0, 3, 1, 1)
        self.delta_tout = QtGui.QLabel(Frame)
        self.delta_tout.setObjectName(_fromUtf8("delta_tout"))
        self.gridLayout.addWidget(self.delta_tout, 1, 0, 1, 1)
        self.editdelta_tout_2 = QtGui.QLineEdit(Frame)
        self.editdelta_tout_2.setObjectName(_fromUtf8("editdelta_tout_2"))
        self.gridLayout.addWidget(self.editdelta_tout_2, 1, 1, 1, 1)
        self.tout = QtGui.QLabel(Frame)
        self.tout.setObjectName(_fromUtf8("tout"))
        self.gridLayout.addWidget(self.tout, 1, 2, 1, 1)
        self.edittout = QtGui.QLineEdit(Frame)
        self.edittout.setObjectName(_fromUtf8("edittout"))
        self.gridLayout.addWidget(self.edittout, 1, 3, 1, 1)
        self.aend = QtGui.QLabel(Frame)
        self.aend.setStatusTip(_fromUtf8(""))
        self.aend.setObjectName(_fromUtf8("aend"))
        self.gridLayout.addWidget(self.aend, 2, 0, 1, 1)
        self.editaend = QtGui.QLineEdit(Frame)
        self.editaend.setObjectName(_fromUtf8("editaend"))
        self.gridLayout.addWidget(self.editaend, 2, 1, 1, 1)
        self.aout = QtGui.QLabel(Frame)
        self.aout.setObjectName(_fromUtf8("aout"))
        self.gridLayout.addWidget(self.aout, 2, 2, 1, 1)
        self.editaout = QtGui.QLineEdit(Frame)
        self.editaout.setObjectName(_fromUtf8("editaout"))
        self.gridLayout.addWidget(self.editaout, 2, 3, 1, 1)
        self.delta_tout_2 = QtGui.QLabel(Frame)
        self.delta_tout_2.setObjectName(_fromUtf8("delta_tout_2"))
        self.gridLayout.addWidget(self.delta_tout_2, 3, 0, 1, 1)
        self.editdelta_tout = QtGui.QLineEdit(Frame)
        self.editdelta_tout.setObjectName(_fromUtf8("editdelta_tout"))
        self.gridLayout.addWidget(self.editdelta_tout, 3, 1, 1, 1)
        self.foutput = QtGui.QLabel(Frame)
        self.foutput.setObjectName(_fromUtf8("foutput"))
        self.gridLayout.addWidget(self.foutput, 3, 2, 1, 1)
        self.editfoutput = QtGui.QLineEdit(Frame)
        self.editfoutput.setObjectName(_fromUtf8("editfoutput"))
        self.gridLayout.addWidget(self.editfoutput, 3, 3, 1, 1)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        Frame.setWindowTitle(_translate("Frame", "Frame", None))
        self.tend.setText(_translate("Frame", "tend", None))
        self.edittend.setStatusTip(_translate("Frame", "edit tend", None))
        self.noutput.setText(_translate("Frame", "noutput", None))
        self.editnoutput.setStatusTip(_translate("Frame", "edit noutput", None))
        self.delta_tout.setText(_translate("Frame", "delta_tout", None))
        self.editdelta_tout_2.setStatusTip(_translate("Frame", "edit delta_tout", None))
        self.tout.setText(_translate("Frame", "tout", None))
        self.edittout.setStatusTip(_translate("Frame", "edit tout", None))
        self.aend.setText(_translate("Frame", "aend", None))
        self.editaend.setStatusTip(_translate("Frame", "edit aend", None))
        self.aout.setText(_translate("Frame", "aout", None))
        self.editaout.setStatusTip(_translate("Frame", "edit aout", None))
        self.delta_tout_2.setText(_translate("Frame", "delta_tout", None))
        self.editdelta_tout.setStatusTip(_translate("Frame", "edit delta_tout", None))
        self.foutput.setText(_translate("Frame", "foutput", None))
        self.editfoutput.setStatusTip(_translate("Frame", "edit foutput", None))

        self.Save.setStatusTip(_translate("Frame", "Save variables", None))
        self.Save.setText(_translate("Frame", "Save", None))
        self.Reset.setStatusTip(_translate("Frame", "Reset value", None))
        self.Reset.setText(_translate("Frame", "Reset", None))






class Boundary_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName(_fromUtf8("Frame"))
        Frame.resize(625, 617)
        Frame.setFrameShape(QtGui.QFrame.StyledPanel)
        Frame.setFrameShadow(QtGui.QFrame.Raised)
        
        self.Save = QtGui.QPushButton(Frame)
        self.Save.setGeometry(QtCore.QRect(0, 0, 85, 27))
        self.Save.setObjectName(_fromUtf8("Save"))
        self.Reset = QtGui.QPushButton(Frame)
        self.Reset.setGeometry(QtCore.QRect(90, 0, 85, 27))
        self.Reset.setObjectName(_fromUtf8("Reset"))



        self.gridLayout = QtGui.QGridLayout(Frame)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.nboundary = QtGui.QLabel(Frame)
        self.nboundary.setStatusTip(_fromUtf8(""))
        self.nboundary.setObjectName(_fromUtf8("nboundary"))
        self.gridLayout.addWidget(self.nboundary, 0, 0, 1, 1)
        self.editnboundary = QtGui.QLineEdit(Frame)
        self.editnboundary.setObjectName(_fromUtf8("editnboundary"))
        self.gridLayout.addWidget(self.editnboundary, 0, 1, 1, 1)
        self.ibound_min = QtGui.QLabel(Frame)
        self.ibound_min.setObjectName(_fromUtf8("ibound_min"))
        self.gridLayout.addWidget(self.ibound_min, 0, 2, 1, 1)
        self.editibound_min = QtGui.QLineEdit(Frame)
        self.editibound_min.setObjectName(_fromUtf8("editibound_min"))
        self.gridLayout.addWidget(self.editibound_min, 0, 3, 1, 1)
        self.bound_type = QtGui.QLabel(Frame)
        self.bound_type.setObjectName(_fromUtf8("bound_type"))
        self.gridLayout.addWidget(self.bound_type, 1, 0, 1, 1)
        self.editbound_type = QtGui.QLineEdit(Frame)
        self.editbound_type.setObjectName(_fromUtf8("editbound_type"))
        self.gridLayout.addWidget(self.editbound_type, 1, 1, 1, 1)
        self.jbound_min = QtGui.QLabel(Frame)
        self.jbound_min.setObjectName(_fromUtf8("jbound_min"))
        self.gridLayout.addWidget(self.jbound_min, 1, 2, 1, 1)
        self.editjbound_min = QtGui.QLineEdit(Frame)
        self.editjbound_min.setObjectName(_fromUtf8("editjbound_min"))
        self.gridLayout.addWidget(self.editjbound_min, 1, 3, 1, 1)
        self.d_bound = QtGui.QLabel(Frame)
        self.d_bound.setStatusTip(_fromUtf8(""))
        self.d_bound.setObjectName(_fromUtf8("d_bound"))
        self.gridLayout.addWidget(self.d_bound, 2, 0, 1, 1)
        self.editd_bound = QtGui.QLineEdit(Frame)
        self.editd_bound.setObjectName(_fromUtf8("editd_bound"))
        self.gridLayout.addWidget(self.editd_bound, 2, 1, 1, 1)
        self.kbound_min = QtGui.QLabel(Frame)
        self.kbound_min.setObjectName(_fromUtf8("kbound_min"))
        self.gridLayout.addWidget(self.kbound_min, 2, 2, 1, 1)
        self.editkbound_min = QtGui.QLineEdit(Frame)
        self.editkbound_min.setObjectName(_fromUtf8("editkbound_min"))
        self.gridLayout.addWidget(self.editkbound_min, 2, 3, 1, 1)
        self.u_bound = QtGui.QLabel(Frame)
        self.u_bound.setObjectName(_fromUtf8("u_bound"))
        self.gridLayout.addWidget(self.u_bound, 3, 0, 1, 1)
        self.editu_bound = QtGui.QLineEdit(Frame)
        self.editu_bound.setObjectName(_fromUtf8("editu_bound"))
        self.gridLayout.addWidget(self.editu_bound, 3, 1, 1, 1)
        self.ibound_max = QtGui.QLabel(Frame)
        self.ibound_max.setObjectName(_fromUtf8("ibound_max"))
        self.gridLayout.addWidget(self.ibound_max, 3, 2, 1, 1)
        self.editibound_max = QtGui.QLineEdit(Frame)
        self.editibound_max.setObjectName(_fromUtf8("editibound_max"))
        self.gridLayout.addWidget(self.editibound_max, 3, 3, 1, 1)
        self.v_bound = QtGui.QLabel(Frame)
        self.v_bound.setObjectName(_fromUtf8("v_bound"))
        self.gridLayout.addWidget(self.v_bound, 4, 0, 1, 1)
        self.editv_bound = QtGui.QLineEdit(Frame)
        self.editv_bound.setObjectName(_fromUtf8("editv_bound"))
        self.gridLayout.addWidget(self.editv_bound, 4, 1, 1, 1)
        self.jbound_max = QtGui.QLabel(Frame)
        self.jbound_max.setObjectName(_fromUtf8("jbound_max"))
        self.gridLayout.addWidget(self.jbound_max, 4, 2, 1, 1)
        self.editjbound_max = QtGui.QLineEdit(Frame)
        self.editjbound_max.setObjectName(_fromUtf8("editjbound_max"))
        self.gridLayout.addWidget(self.editjbound_max, 4, 3, 1, 1)
        self.w_bound = QtGui.QLabel(Frame)
        self.w_bound.setObjectName(_fromUtf8("w_bound"))
        self.gridLayout.addWidget(self.w_bound, 5, 0, 1, 1)
        self.editw_bound = QtGui.QLineEdit(Frame)
        self.editw_bound.setObjectName(_fromUtf8("editw_bound"))
        self.gridLayout.addWidget(self.editw_bound, 5, 1, 1, 1)
        self.kbound_max = QtGui.QLabel(Frame)
        self.kbound_max.setObjectName(_fromUtf8("kbound_max"))
        self.gridLayout.addWidget(self.kbound_max, 5, 2, 1, 1)
        self.editkbound_max = QtGui.QLineEdit(Frame)
        self.editkbound_max.setObjectName(_fromUtf8("editkbound_max"))
        self.gridLayout.addWidget(self.editkbound_max, 5, 3, 1, 1)
        self.p_bound = QtGui.QLabel(Frame)
        self.p_bound.setObjectName(_fromUtf8("p_bound"))
        self.gridLayout.addWidget(self.p_bound, 6, 0, 1, 1)
        self.editp_bound = QtGui.QLineEdit(Frame)
        self.editp_bound.setObjectName(_fromUtf8("editp_bound"))
        self.gridLayout.addWidget(self.editp_bound, 6, 1, 1, 1)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        Frame.setWindowTitle(_translate("Frame", "Frame", None))
        self.nboundary.setText(_translate("Frame", "nboundary", None))
        self.editnboundary.setStatusTip(_translate("Frame", "edit nboundary", None))
        self.ibound_min.setText(_translate("Frame", "ibound_min", None))
        self.editibound_min.setStatusTip(_translate("Frame", "edit ibound_min", None))
        self.bound_type.setText(_translate("Frame", "bound_type", None))
        self.editbound_type.setStatusTip(_translate("Frame", "edit bound_type", None))
        self.jbound_min.setText(_translate("Frame", "jbound_min", None))
        self.editjbound_min.setStatusTip(_translate("Frame", "edit jbound_min", None))
        self.d_bound.setText(_translate("Frame", "d_bound", None))
        self.editd_bound.setStatusTip(_translate("Frame", "edit d_bound", None))
        self.kbound_min.setText(_translate("Frame", "kbound_min", None))
        self.editkbound_min.setStatusTip(_translate("Frame", "edit kbound_min", None))
        self.u_bound.setText(_translate("Frame", "u_bound", None))
        self.editu_bound.setStatusTip(_translate("Frame", "edit u_bound", None))
        self.ibound_max.setText(_translate("Frame", "ibound_max", None))
        self.editibound_max.setStatusTip(_translate("Frame", "edit ibound_max", None))
        self.v_bound.setText(_translate("Frame", "v_bound", None))
        self.editv_bound.setStatusTip(_translate("Frame", "edit v_bound", None))
        self.jbound_max.setText(_translate("Frame", "jbound_max", None))
        self.editjbound_max.setStatusTip(_translate("Frame", "edit jbound_max", None))
        self.w_bound.setText(_translate("Frame", "w_bound", None))
        self.editw_bound.setStatusTip(_translate("Frame", "edit w_bound", None))
        self.kbound_max.setText(_translate("Frame", "kbound_max", None))
        self.editkbound_max.setStatusTip(_translate("Frame", "edit kbound_max", None))
        self.p_bound.setText(_translate("Frame", "p_bound", None))
        self.editp_bound.setStatusTip(_translate("Frame", "edit p_bound", None))

        self.Save.setStatusTip(_translate("Frame", "Save variables", None))
        self.Save.setText(_translate("Frame", "Save", None))
        self.Reset.setStatusTip(_translate("Frame", "Reset value", None))
        self.Reset.setText(_translate("Frame", "Reset", None))

class Global_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName(_fromUtf8("Frame"))
        Frame.resize(615, 540)
        Frame.setFrameShape(QtGui.QFrame.StyledPanel)
        Frame.setFrameShadow(QtGui.QFrame.Raised)


        self.Save = QtGui.QPushButton(Frame)
        self.Save.setGeometry(QtCore.QRect(0, 0, 85, 27))
        self.Save.setObjectName(_fromUtf8("Save"))
        self.Reset = QtGui.QPushButton(Frame)
        self.Reset.setGeometry(QtCore.QRect(90, 0, 85, 27))
        self.Reset.setObjectName(_fromUtf8("Reset"))



        self.edithydro = QtGui.QLineEdit(Frame)
        self.edithydro.setGeometry(QtCore.QRect(94, 291, 146, 33))
        self.edithydro.setObjectName(_fromUtf8("edithydro"))
        self.ordering = QtGui.QLabel(Frame)
        self.ordering.setGeometry(QtCore.QRect(314, 291, 78, 21))
        self.ordering.setObjectName(_fromUtf8("ordering"))
        self.nrestart = QtGui.QLabel(Frame)
        self.nrestart.setGeometry(QtCore.QRect(10, 451, 60, 21))
        self.nrestart.setObjectName(_fromUtf8("nrestart"))
        self.editnrestart = QtGui.QLineEdit(Frame)
        self.editnrestart.setGeometry(QtCore.QRect(94, 451, 146, 33))
        self.editnrestart.setObjectName(_fromUtf8("editnrestart"))
        self.editnstepmax = QtGui.QLineEdit(Frame)
        self.editnstepmax.setGeometry(QtCore.QRect(402, 51, 146, 33))
        self.editnstepmax.setObjectName(_fromUtf8("editnstepmax"))
        self.nboundary = QtGui.QLabel(Frame)
        self.nboundary.setGeometry(QtCore.QRect(10, 51, 68, 21))
        self.nboundary.setStatusTip(_fromUtf8(""))
        self.nboundary.setObjectName(_fromUtf8("nboundary"))
        self.editcosmo = QtGui.QLineEdit(Frame)
        self.editcosmo.setGeometry(QtCore.QRect(94, 51, 146, 33))
        self.editcosmo.setObjectName(_fromUtf8("editcosmo"))
        self.nremap = QtGui.QLabel(Frame)
        self.nremap.setGeometry(QtCore.QRect(314, 211, 78, 21))
        self.nremap.setObjectName(_fromUtf8("nremap"))
        self.editnremap = QtGui.QLineEdit(Frame)
        self.editnremap.setGeometry(QtCore.QRect(402, 211, 146, 33))
        self.editnremap.setObjectName(_fromUtf8("editnremap"))
        self.editpic = QtGui.QLineEdit(Frame)
        self.editpic.setGeometry(QtCore.QRect(94, 131, 146, 33))
        self.editpic.setObjectName(_fromUtf8("editpic"))
        self.hydro = QtGui.QLabel(Frame)
        self.hydro.setGeometry(QtCore.QRect(10, 291, 56, 21))
        self.hydro.setObjectName(_fromUtf8("hydro"))
        self.editpoisson = QtGui.QLineEdit(Frame)
        self.editpoisson.setGeometry(QtCore.QRect(94, 211, 146, 33))
        self.editpoisson.setObjectName(_fromUtf8("editpoisson"))
        self.nstepmax = QtGui.QLabel(Frame)
        self.nstepmax.setGeometry(QtCore.QRect(314, 51, 74, 21))
        self.nstepmax.setObjectName(_fromUtf8("nstepmax"))
        self.pic = QtGui.QLabel(Frame)
        self.pic.setGeometry(QtCore.QRect(10, 131, 78, 21))
        self.pic.setObjectName(_fromUtf8("pic"))
        self.ncontrol = QtGui.QLabel(Frame)
        self.ncontrol.setGeometry(QtCore.QRect(314, 131, 74, 21))
        self.ncontrol.setObjectName(_fromUtf8("ncontrol"))
        self.editncontrol = QtGui.QLineEdit(Frame)
        self.editncontrol.setGeometry(QtCore.QRect(402, 131, 146, 33))
        self.editncontrol.setObjectName(_fromUtf8("editncontrol"))
        self.nsubcycle = QtGui.QLabel(Frame)
        self.nsubcycle.setGeometry(QtCore.QRect(314, 371, 78, 21))
        self.nsubcycle.setObjectName(_fromUtf8("nsubcycle"))
        self.editnsubcycle = QtGui.QLineEdit(Frame)
        self.editnsubcycle.setGeometry(QtCore.QRect(402, 371, 146, 33))
        self.editnsubcycle.setObjectName(_fromUtf8("editnsubcycle"))
        self.poisson = QtGui.QLabel(Frame)
        self.poisson.setGeometry(QtCore.QRect(10, 211, 56, 21))
        self.poisson.setStatusTip(_fromUtf8(""))
        self.poisson.setObjectName(_fromUtf8("poisson"))
        self.verbose = QtGui.QLabel(Frame)
        self.verbose.setGeometry(QtCore.QRect(10, 371, 55, 21))
        self.verbose.setObjectName(_fromUtf8("verbose"))
        self.editverbose = QtGui.QLineEdit(Frame)
        self.editverbose.setGeometry(QtCore.QRect(94, 371, 146, 33))
        self.editverbose.setObjectName(_fromUtf8("editverbose"))
        self.editordering = QtGui.QLineEdit(Frame)
        self.editordering.setGeometry(QtCore.QRect(402, 291, 146, 33))
        self.editordering.setObjectName(_fromUtf8("editordering"))

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        Frame.setWindowTitle(_translate("Frame", "Frame", None))
        self.edithydro.setStatusTip(_translate("Frame", "edit hydro", None))
        self.ordering.setText(_translate("Frame", "ordering", None))
        self.nrestart.setText(_translate("Frame", "nrestart", None))
        self.editnrestart.setStatusTip(_translate("Frame", "edit nrestart", None))
        self.editnstepmax.setStatusTip(_translate("Frame", "edit nstepmax", None))
        self.nboundary.setText(_translate("Frame", "Frame", None))
        self.editcosmo.setStatusTip(_translate("Frame", "edit Frame", None))
        self.nremap.setText(_translate("Frame", "nremap", None))
        self.editnremap.setStatusTip(_translate("Frame", "edit nremap", None))
        self.editpic.setStatusTip(_translate("Frame", "edit pic", None))
        self.hydro.setText(_translate("Frame", "hydro", None))
        self.editpoisson.setStatusTip(_translate("Frame", "edit poisson", None))
        self.nstepmax.setText(_translate("Frame", "nstepmax", None))
        self.pic.setText(_translate("Frame", "pic", None))
        self.ncontrol.setText(_translate("Frame", "ncontrol", None))
        self.editncontrol.setStatusTip(_translate("Frame", "edit ncontrol", None))
        self.nsubcycle.setText(_translate("Frame", "nsubcycle", None))
        self.editnsubcycle.setStatusTip(_translate("Frame", "edit nsubcycle", None))
        self.poisson.setText(_translate("Frame", "poisson", None))
        self.verbose.setText(_translate("Frame", "verbose", None))
        self.editverbose.setStatusTip(_translate("Frame", "edit verbose", None))
        self.editordering.setStatusTip(_translate("Frame", "edit ordering", None))

        self.Save.setStatusTip(_translate("Frame", "Save variables", None))
        self.Save.setText(_translate("Frame", "Save", None))
        self.Reset.setStatusTip(_translate("Frame", "Reset value", None))
        self.Reset.setText(_translate("Frame", "Reset", None))






class Hydro_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName(_fromUtf8("Frame"))
        Frame.resize(595, 458)
        Frame.setFrameShape(QtGui.QFrame.StyledPanel)
        Frame.setFrameShadow(QtGui.QFrame.Raised)

        self.Save = QtGui.QPushButton(Frame)
        self.Save.setGeometry(QtCore.QRect(0, 0, 85, 27))
        self.Save.setObjectName(_fromUtf8("Save"))
        self.Reset = QtGui.QPushButton(Frame)
        self.Reset.setGeometry(QtCore.QRect(90, 0, 85, 27))
        self.Reset.setObjectName(_fromUtf8("Reset"))




        self.editsmallc = QtGui.QLineEdit(Frame)
        self.editsmallc.setGeometry(QtCore.QRect(94, 291, 146, 33))
        self.editsmallc.setObjectName(_fromUtf8("editsmallc"))
        self.pressure_fix = QtGui.QLabel(Frame)
        self.pressure_fix.setGeometry(QtCore.QRect(314, 291, 78, 21))
        self.pressure_fix.setObjectName(_fromUtf8("pressure_fix"))
        self.editriemann2d = QtGui.QLineEdit(Frame)
        self.editriemann2d.setGeometry(QtCore.QRect(402, 51, 146, 33))
        self.editriemann2d.setObjectName(_fromUtf8("editriemann2d"))
        self.gamma = QtGui.QLabel(Frame)
        self.gamma.setGeometry(QtCore.QRect(10, 51, 68, 21))
        self.gamma.setStatusTip(_fromUtf8(""))
        self.gamma.setObjectName(_fromUtf8("gamma"))
        self.editgamma = QtGui.QLineEdit(Frame)
        self.editgamma.setGeometry(QtCore.QRect(94, 51, 146, 33))
        self.editgamma.setObjectName(_fromUtf8("editgamma"))
        self.slope_type = QtGui.QLabel(Frame)
        self.slope_type.setGeometry(QtCore.QRect(314, 211, 78, 21))
        self.slope_type.setObjectName(_fromUtf8("slope_type"))
        self.editslope_type = QtGui.QLineEdit(Frame)
        self.editslope_type.setGeometry(QtCore.QRect(402, 211, 146, 33))
        self.editslope_type.setObjectName(_fromUtf8("editslope_type"))
        self.editcourant_factor = QtGui.QLineEdit(Frame)
        self.editcourant_factor.setGeometry(QtCore.QRect(94, 131, 146, 33))
        self.editcourant_factor.setObjectName(_fromUtf8("editcourant_factor"))
        self.smallc = QtGui.QLabel(Frame)
        self.smallc.setGeometry(QtCore.QRect(10, 291, 56, 21))
        self.smallc.setObjectName(_fromUtf8("smallc"))
        self.editsmallr = QtGui.QLineEdit(Frame)
        self.editsmallr.setGeometry(QtCore.QRect(94, 211, 146, 33))
        self.editsmallr.setObjectName(_fromUtf8("editsmallr"))
        self.riemann2d = QtGui.QLabel(Frame)
        self.riemann2d.setGeometry(QtCore.QRect(314, 51, 74, 21))
        self.riemann2d.setObjectName(_fromUtf8("riemann2d"))
        self.courant_factor = QtGui.QLabel(Frame)
        self.courant_factor.setGeometry(QtCore.QRect(10, 131, 78, 21))
        self.courant_factor.setObjectName(_fromUtf8("courant_factor"))
        self.niter_riemann = QtGui.QLabel(Frame)
        self.niter_riemann.setGeometry(QtCore.QRect(314, 131, 74, 21))
        self.niter_riemann.setObjectName(_fromUtf8("niter_riemann"))
        self.editniter_riemann = QtGui.QLineEdit(Frame)
        self.editniter_riemann.setGeometry(QtCore.QRect(402, 131, 146, 33))
        self.editniter_riemann.setObjectName(_fromUtf8("editniter_riemann"))
        self.smallr = QtGui.QLabel(Frame)
        self.smallr.setGeometry(QtCore.QRect(10, 211, 56, 21))
        self.smallr.setStatusTip(_fromUtf8(""))
        self.smallr.setObjectName(_fromUtf8("smallr"))
        self.riemann = QtGui.QLabel(Frame)
        self.riemann.setGeometry(QtCore.QRect(10, 371, 55, 21))
        self.riemann.setObjectName(_fromUtf8("riemann"))
        self.editriemann = QtGui.QLineEdit(Frame)
        self.editriemann.setGeometry(QtCore.QRect(94, 371, 146, 33))
        self.editriemann.setObjectName(_fromUtf8("editriemann"))
        self.editpressure_fix = QtGui.QLineEdit(Frame)
        self.editpressure_fix.setGeometry(QtCore.QRect(402, 291, 146, 33))
        self.editpressure_fix.setObjectName(_fromUtf8("editpressure_fix"))

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        Frame.setWindowTitle(_translate("Frame", "Frame", None))
        self.editsmallc.setStatusTip(_translate("Frame", "edit smallc", None))
        self.pressure_fix.setText(_translate("Frame", "pressure_fix", None))
        self.editriemann2d.setStatusTip(_translate("Frame", "edit riemann2d", None))
        self.gamma.setText(_translate("Frame", "gamma", None))
        self.editgamma.setStatusTip(_translate("Frame", "edit gamma", None))
        self.slope_type.setText(_translate("Frame", "slope_type", None))
        self.editslope_type.setStatusTip(_translate("Frame", "edit slope_type", None))
        self.editcourant_factor.setStatusTip(_translate("Frame", "edit courant_factor", None))
        self.smallc.setText(_translate("Frame", "smallc", None))
        self.editsmallr.setStatusTip(_translate("Frame", "edit smallr", None))
        self.riemann2d.setText(_translate("Frame", "riemann2d", None))
        self.courant_factor.setText(_translate("Frame", "courant_factor", None))
        self.niter_riemann.setText(_translate("Frame", "niter_riemann", None))
        self.editniter_riemann.setStatusTip(_translate("Frame", "edit niter_riemann", None))
        self.smallr.setText(_translate("Frame", "smallr", None))
        self.riemann.setText(_translate("Frame", "riemann", None))
        self.editriemann.setStatusTip(_translate("Frame", "edit riemann", None))
        self.editpressure_fix.setStatusTip(_translate("Frame", "edit pressure_fix", None))

        self.Save.setStatusTip(_translate("Frame", "Save variables", None))
        self.Save.setText(_translate("Frame", "Save", None))
        self.Reset.setStatusTip(_translate("Frame", "Reset value", None))
        self.Reset.setText(_translate("Frame", "Reset", None))






class Refine_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName(_fromUtf8("Frame"))
        Frame.resize(763, 555)
        Frame.setFrameShape(QtGui.QFrame.StyledPanel)
        Frame.setFrameShadow(QtGui.QFrame.Raised)

        
        self.Save = QtGui.QPushButton(Frame)
        self.Save.setGeometry(QtCore.QRect(0, 0, 85, 27))
        self.Save.setObjectName(_fromUtf8("Save"))
        self.Reset = QtGui.QPushButton(Frame)
        self.Reset.setGeometry(QtCore.QRect(90, 0, 85, 27))
        self.Reset.setObjectName(_fromUtf8("Reset"))

        self.gridLayout = QtGui.QGridLayout(Frame)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.mass_sph = QtGui.QLabel(Frame)
        self.mass_sph.setStatusTip(_fromUtf8(""))
        self.mass_sph.setObjectName(_fromUtf8("mass_sph"))
        self.gridLayout.addWidget(self.mass_sph, 0, 0, 1, 1)
        self.editmass_sph = QtGui.QLineEdit(Frame)
        self.editmass_sph.setObjectName(_fromUtf8("editmass_sph"))
        self.gridLayout.addWidget(self.editmass_sph, 0, 1, 1, 1)
        self.floor_d = QtGui.QLabel(Frame)
        self.floor_d.setObjectName(_fromUtf8("floor_d"))
        self.gridLayout.addWidget(self.floor_d, 0, 2, 1, 1)
        self.editfloor_d = QtGui.QLineEdit(Frame)
        self.editfloor_d.setObjectName(_fromUtf8("editfloor_d"))
        self.gridLayout.addWidget(self.editfloor_d, 0, 3, 1, 1)
        self.err_grad_d = QtGui.QLabel(Frame)
        self.err_grad_d.setObjectName(_fromUtf8("err_grad_d"))
        self.gridLayout.addWidget(self.err_grad_d, 0, 4, 1, 1)
        self.editerr_grad_d = QtGui.QLineEdit(Frame)
        self.editerr_grad_d.setObjectName(_fromUtf8("editerr_grad_d"))
        self.gridLayout.addWidget(self.editerr_grad_d, 0, 5, 1, 2)
        self.courant_factor = QtGui.QLabel(Frame)
        self.courant_factor.setObjectName(_fromUtf8("courant_factor"))
        self.gridLayout.addWidget(self.courant_factor, 1, 0, 1, 1)
        self.editm_refine = QtGui.QLineEdit(Frame)
        self.editm_refine.setObjectName(_fromUtf8("editm_refine"))
        self.gridLayout.addWidget(self.editm_refine, 1, 1, 1, 1)
        self.floor_u = QtGui.QLabel(Frame)
        self.floor_u.setObjectName(_fromUtf8("floor_u"))
        self.gridLayout.addWidget(self.floor_u, 1, 2, 1, 1)
        self.editfloor_u = QtGui.QLineEdit(Frame)
        self.editfloor_u.setObjectName(_fromUtf8("editfloor_u"))
        self.gridLayout.addWidget(self.editfloor_u, 1, 3, 1, 1)
        self.err_grad_u = QtGui.QLabel(Frame)
        self.err_grad_u.setObjectName(_fromUtf8("err_grad_u"))
        self.gridLayout.addWidget(self.err_grad_u, 1, 4, 1, 1)
        self.editerr_grad_u = QtGui.QLineEdit(Frame)
        self.editerr_grad_u.setObjectName(_fromUtf8("editerr_grad_u"))
        self.gridLayout.addWidget(self.editerr_grad_u, 1, 6, 1, 1)
        self.jeans_refine = QtGui.QLabel(Frame)
        self.jeans_refine.setStatusTip(_fromUtf8(""))
        self.jeans_refine.setObjectName(_fromUtf8("jeans_refine"))
        self.gridLayout.addWidget(self.jeans_refine, 2, 0, 1, 1)
        self.editjeans_refine = QtGui.QLineEdit(Frame)
        self.editjeans_refine.setObjectName(_fromUtf8("editjeans_refine"))
        self.gridLayout.addWidget(self.editjeans_refine, 2, 1, 1, 1)
        self.floor_p = QtGui.QLabel(Frame)
        self.floor_p.setObjectName(_fromUtf8("floor_p"))
        self.gridLayout.addWidget(self.floor_p, 2, 2, 1, 1)
        self.editfloor_p = QtGui.QLineEdit(Frame)
        self.editfloor_p.setObjectName(_fromUtf8("editfloor_p"))
        self.gridLayout.addWidget(self.editfloor_p, 2, 3, 1, 1)
        self.err_grad_p = QtGui.QLabel(Frame)
        self.err_grad_p.setObjectName(_fromUtf8("err_grad_p"))
        self.gridLayout.addWidget(self.err_grad_p, 2, 4, 1, 1)
        self.editerr_grad_p = QtGui.QLineEdit(Frame)
        self.editerr_grad_p.setObjectName(_fromUtf8("editerr_grad_p"))
        self.gridLayout.addWidget(self.editerr_grad_p, 2, 6, 1, 1)
        self.x_refine = QtGui.QLabel(Frame)
        self.x_refine.setObjectName(_fromUtf8("x_refine"))
        self.gridLayout.addWidget(self.x_refine, 3, 0, 1, 1)
        self.editx_refine = QtGui.QLineEdit(Frame)
        self.editx_refine.setObjectName(_fromUtf8("editx_refine"))
        self.gridLayout.addWidget(self.editx_refine, 3, 1, 1, 1)
        self.r_refine = QtGui.QLabel(Frame)
        self.r_refine.setObjectName(_fromUtf8("r_refine"))
        self.gridLayout.addWidget(self.r_refine, 3, 2, 1, 1)
        self.editr_refine = QtGui.QLineEdit(Frame)
        self.editr_refine.setObjectName(_fromUtf8("editr_refine"))
        self.gridLayout.addWidget(self.editr_refine, 3, 3, 1, 1)
        self.exp_refine = QtGui.QLabel(Frame)
        self.exp_refine.setObjectName(_fromUtf8("exp_refine"))
        self.gridLayout.addWidget(self.exp_refine, 3, 4, 1, 1)
        self.editexp_refine = QtGui.QLineEdit(Frame)
        self.editexp_refine.setObjectName(_fromUtf8("editexp_refine"))
        self.gridLayout.addWidget(self.editexp_refine, 3, 6, 1, 1)
        self.y_refine = QtGui.QLabel(Frame)
        self.y_refine.setObjectName(_fromUtf8("y_refine"))
        self.gridLayout.addWidget(self.y_refine, 4, 0, 1, 1)
        self.edity_refine = QtGui.QLineEdit(Frame)
        self.edity_refine.setObjectName(_fromUtf8("edity_refine"))
        self.gridLayout.addWidget(self.edity_refine, 4, 1, 1, 1)
        self.a_refine = QtGui.QLabel(Frame)
        self.a_refine.setObjectName(_fromUtf8("a_refine"))
        self.gridLayout.addWidget(self.a_refine, 4, 2, 1, 1)
        self.edita_refine_2 = QtGui.QLineEdit(Frame)
        self.edita_refine_2.setObjectName(_fromUtf8("edita_refine_2"))
        self.gridLayout.addWidget(self.edita_refine_2, 4, 3, 1, 1)
        self.interpol_var = QtGui.QLabel(Frame)
        self.interpol_var.setObjectName(_fromUtf8("interpol_var"))
        self.gridLayout.addWidget(self.interpol_var, 4, 4, 1, 1)
        self.editinterpol_var = QtGui.QLineEdit(Frame)
        self.editinterpol_var.setObjectName(_fromUtf8("editinterpol_var"))
        self.gridLayout.addWidget(self.editinterpol_var, 4, 6, 1, 1)
        self.z_refine = QtGui.QLabel(Frame)
        self.z_refine.setObjectName(_fromUtf8("z_refine"))
        self.gridLayout.addWidget(self.z_refine, 5, 0, 1, 1)
        self.editz_refine = QtGui.QLineEdit(Frame)
        self.editz_refine.setObjectName(_fromUtf8("editz_refine"))
        self.gridLayout.addWidget(self.editz_refine, 5, 1, 1, 1)
        self.b_refine = QtGui.QLabel(Frame)
        self.b_refine.setObjectName(_fromUtf8("b_refine"))
        self.gridLayout.addWidget(self.b_refine, 5, 2, 1, 1)
        self.editb_refine = QtGui.QLineEdit(Frame)
        self.editb_refine.setObjectName(_fromUtf8("editb_refine"))
        self.gridLayout.addWidget(self.editb_refine, 5, 3, 1, 1)
        self.interpol_type = QtGui.QLabel(Frame)
        self.interpol_type.setObjectName(_fromUtf8("interpol_type"))
        self.gridLayout.addWidget(self.interpol_type, 5, 4, 1, 2)
        self.editinterpol_type = QtGui.QLineEdit(Frame)
        self.editinterpol_type.setObjectName(_fromUtf8("editinterpol_type"))
        self.gridLayout.addWidget(self.editinterpol_type, 5, 6, 1, 1)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        Frame.setWindowTitle(_translate("Frame", "Frame", None))
        self.mass_sph.setText(_translate("Frame", "mass_sph", None))
        self.editmass_sph.setStatusTip(_translate("Frame", "edit mass_sph", None))
        self.floor_d.setText(_translate("Frame", "floor_d", None))
        self.editfloor_d.setStatusTip(_translate("Frame", "edit floor_d", None))
        self.err_grad_d.setText(_translate("Frame", "err_grad_d", None))
        self.editerr_grad_d.setStatusTip(_translate("Frame", "edit err_grad_d", None))
        self.courant_factor.setText(_translate("Frame", "m_refine", None))
        self.editm_refine.setStatusTip(_translate("Frame", "edit m_refine", None))
        self.floor_u.setText(_translate("Frame", "floor_u", None))
        self.editfloor_u.setStatusTip(_translate("Frame", "edit floor_u", None))
        self.err_grad_u.setText(_translate("Frame", "err_grad_u", None))
        self.editerr_grad_u.setStatusTip(_translate("Frame", "edit err_grad_u", None))
        self.jeans_refine.setText(_translate("Frame", "jeans_refine", None))
        self.editjeans_refine.setStatusTip(_translate("Frame", "edit jeans_refine", None))
        self.floor_p.setText(_translate("Frame", "floor_p", None))
        self.editfloor_p.setStatusTip(_translate("Frame", "edit floor_p", None))
        self.err_grad_p.setText(_translate("Frame", "err_grad_p", None))
        self.editerr_grad_p.setStatusTip(_translate("Frame", "edit err_grad_p", None))
        self.x_refine.setText(_translate("Frame", "x_refine", None))
        self.editx_refine.setStatusTip(_translate("Frame", "edit x_refine", None))
        self.r_refine.setText(_translate("Frame", "r_refine", None))
        self.editr_refine.setStatusTip(_translate("Frame", "edit r_refine", None))
        self.exp_refine.setText(_translate("Frame", "exp_refine", None))
        self.editexp_refine.setStatusTip(_translate("Frame", "edit exp_refine", None))
        self.y_refine.setText(_translate("Frame", "y_refine", None))
        self.edity_refine.setStatusTip(_translate("Frame", "edit y_refine", None))
        self.a_refine.setText(_translate("Frame", "a_refine", None))
        self.edita_refine_2.setStatusTip(_translate("Frame", "edit a_refine", None))
        self.interpol_var.setText(_translate("Frame", "interpol_var", None))
        self.editinterpol_var.setStatusTip(_translate("Frame", "edit interpol_var", None))
        self.z_refine.setText(_translate("Frame", "z_refine", None))
        self.editz_refine.setStatusTip(_translate("Frame", "edit z_refine", None))
        self.b_refine.setText(_translate("Frame", "b_refine", None))
        self.editb_refine.setStatusTip(_translate("Frame", "edit b_refine", None))
        self.interpol_type.setText(_translate("Frame", "interpol_type", None))
        self.editinterpol_type.setStatusTip(_translate("Frame", "edit interpol_type", None))

        self.Save.setStatusTip(_translate("Frame", "Save variables", None))
        self.Save.setText(_translate("Frame", "Save", None))
        self.Reset.setStatusTip(_translate("Frame", "Reset value", None))
        self.Reset.setText(_translate("Frame", "Reset", None))






class Poisson_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName(_fromUtf8("Frame"))
        Frame.resize(548, 278)
        Frame.setFrameShape(QtGui.QFrame.StyledPanel)
        Frame.setFrameShadow(QtGui.QFrame.Raised)

        
        self.Save = QtGui.QPushButton(Frame)
        self.Save.setGeometry(QtCore.QRect(0, 0, 85, 27))
        self.Save.setObjectName(_fromUtf8("Save"))
        self.Reset = QtGui.QPushButton(Frame)
        self.Reset.setGeometry(QtCore.QRect(90, 0, 85, 27))
        self.Reset.setObjectName(_fromUtf8("Reset"))

        self.gridLayout = QtGui.QGridLayout(Frame)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.gravity_type = QtGui.QLabel(Frame)
        self.gravity_type.setStatusTip(_fromUtf8(""))
        self.gravity_type.setObjectName(_fromUtf8("gravity_type"))
        self.gridLayout.addWidget(self.gravity_type, 0, 0, 1, 1)
        self.editgravity_type = QtGui.QLineEdit(Frame)
        self.editgravity_type.setObjectName(_fromUtf8("editgravity_type"))
        self.gridLayout.addWidget(self.editgravity_type, 0, 1, 1, 1)
        self.cg_levelmin = QtGui.QLabel(Frame)
        self.cg_levelmin.setObjectName(_fromUtf8("cg_levelmin"))
        self.gridLayout.addWidget(self.cg_levelmin, 0, 2, 1, 1)
        self.editcg_levelmin = QtGui.QLineEdit(Frame)
        self.editcg_levelmin.setObjectName(_fromUtf8("editcg_levelmin"))
        self.gridLayout.addWidget(self.editcg_levelmin, 0, 3, 1, 2)
        self.epsilon = QtGui.QLabel(Frame)
        self.epsilon.setObjectName(_fromUtf8("epsilon"))
        self.gridLayout.addWidget(self.epsilon, 1, 0, 1, 1)
        self.editepsilon = QtGui.QLineEdit(Frame)
        self.editepsilon.setObjectName(_fromUtf8("editepsilon"))
        self.gridLayout.addWidget(self.editepsilon, 1, 1, 1, 1)
        self.cic_levelmax = QtGui.QLabel(Frame)
        self.cic_levelmax.setObjectName(_fromUtf8("cic_levelmax"))
        self.gridLayout.addWidget(self.cic_levelmax, 1, 2, 1, 2)
        self.editcic_levelmax = QtGui.QLineEdit(Frame)
        self.editcic_levelmax.setObjectName(_fromUtf8("editcic_levelmax"))
        self.gridLayout.addWidget(self.editcic_levelmax, 1, 4, 1, 1)
        self.gravity_params = QtGui.QLabel(Frame)
        self.gravity_params.setStatusTip(_fromUtf8(""))
        self.gravity_params.setObjectName(_fromUtf8("gravity_params"))
        self.gridLayout.addWidget(self.gravity_params, 2, 0, 1, 1)
        self.editgravity_params = QtGui.QLineEdit(Frame)
        self.editgravity_params.setObjectName(_fromUtf8("editgravity_params"))
        self.gridLayout.addWidget(self.editgravity_params, 2, 1, 1, 1)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        Frame.setWindowTitle(_translate("Frame", "Frame", None))
        self.gravity_type.setText(_translate("Frame", "gravity_type", None))
        self.editgravity_type.setStatusTip(_translate("Frame", "edit gravity_type", None))
        self.cg_levelmin.setText(_translate("Frame", "cg_levelmin", None))
        self.editcg_levelmin.setStatusTip(_translate("Frame", "edit cg_levelmin", None))
        self.epsilon.setText(_translate("Frame", "epsilon", None))
        self.editepsilon.setStatusTip(_translate("Frame", "edit epsilon", None))
        self.cic_levelmax.setText(_translate("Frame", "cic_levelmax", None))
        self.editcic_levelmax.setStatusTip(_translate("Frame", "edit cic_levelmax", None))
        self.gravity_params.setText(_translate("Frame", "gravity_params", None))
        self.editgravity_params.setStatusTip(_translate("Frame", "edit gravity_params", None))

        self.Save.setStatusTip(_translate("Frame", "Save variables", None))
        self.Save.setText(_translate("Frame", "Save", None))
        self.Reset.setStatusTip(_translate("Frame", "Reset value", None))
        self.Reset.setText(_translate("Frame", "Reset", None))


