import sys
from PyQt4 import QtCore, QtGui
try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)





class Phy_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName(_fromUtf8("Frame"))
        Frame.resize(736, 564)
        Frame.setFrameShape(QtGui.QFrame.StyledPanel)
        Frame.setFrameShadow(QtGui.QFrame.Raised)

       

        self.Save = QtGui.QPushButton(Frame)
        self.Save.setGeometry(QtCore.QRect(0, 0, 85, 27))
        self.Save.setObjectName(_fromUtf8("Save"))
        self.Reset = QtGui.QPushButton(Frame)
        self.Reset.setGeometry(QtCore.QRect(90, 0, 85, 27))
        self.Reset.setObjectName(_fromUtf8("Reset"))


        self.gridLayout = QtGui.QGridLayout(Frame)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.a_reion = QtGui.QLabel(Frame)
        self.a_reion.setObjectName(_fromUtf8("a_reion"))
        self.gridLayout.addWidget(self.a_reion, 6, 0, 1, 1)
        self.isothermal = QtGui.QLabel(Frame)
        self.isothermal.setObjectName(_fromUtf8("isothermal"))
        self.gridLayout.addWidget(self.isothermal, 1, 0, 1, 1)
        self.isothermal_2 = QtGui.QLineEdit(Frame)
        self.isothermal_2.setObjectName(_fromUtf8("isothermal_2"))
        self.gridLayout.addWidget(self.isothermal_2, 1, 1, 1, 1)
        self.aspec = QtGui.QLabel(Frame)
        self.aspec.setObjectName(_fromUtf8("aspec"))
        self.gridLayout.addWidget(self.aspec, 5, 0, 1, 1)
        self.metal = QtGui.QLabel(Frame)
        self.metal.setObjectName(_fromUtf8("metal"))
        self.gridLayout.addWidget(self.metal, 2, 0, 1, 1)
        self.cooling = QtGui.QLabel(Frame)
        self.cooling.setObjectName(_fromUtf8("cooling"))
        self.gridLayout.addWidget(self.cooling, 0, 0, 1, 1)
        self.cooling_2 = QtGui.QLineEdit(Frame)
        self.cooling_2.setObjectName(_fromUtf8("cooling_2"))
        self.gridLayout.addWidget(self.cooling_2, 0, 1, 1, 1)
        self.tstar = QtGui.QLineEdit(Frame)
        self.tstar.setObjectName(_fromUtf8("tstar"))
        self.gridLayout.addWidget(self.tstar, 0, 3, 1, 1)
        self.f_w = QtGui.QLabel(Frame)
        self.f_w.setObjectName(_fromUtf8("f_w"))
        self.gridLayout.addWidget(self.f_w, 4, 2, 1, 1)
        self.f_w_2 = QtGui.QLineEdit(Frame)
        self.f_w_2.setObjectName(_fromUtf8("f_w_2"))
        self.gridLayout.addWidget(self.f_w_2, 4, 3, 1, 1)
        self.gstar_2 = QtGui.QLineEdit(Frame)
        self.gstar_2.setObjectName(_fromUtf8("gstar_2"))
        self.gridLayout.addWidget(self.gstar_2, 2, 3, 1, 1)
        self.yld = QtGui.QLabel(Frame)
        self.yld.setObjectName(_fromUtf8("yield"))
        self.gridLayout.addWidget(self.yld, 3, 2, 1, 1)
        self.yield_2 = QtGui.QLineEdit(Frame)
        self.yield_2.setObjectName(_fromUtf8("yield_2"))
        self.gridLayout.addWidget(self.yield_2, 3, 3, 1, 1)
        self.startime = QtGui.QLabel(Frame)
        self.startime.setObjectName(_fromUtf8("startime"))
        self.gridLayout.addWidget(self.startime, 0, 2, 1, 1)
        self.delstar = QtGui.QLabel(Frame)
        self.delstar.setObjectName(_fromUtf8("delstar"))
        self.gridLayout.addWidget(self.delstar, 1, 2, 1, 1)
        self.delstar_2 = QtGui.QLineEdit(Frame)
        self.delstar_2.setObjectName(_fromUtf8("delstar_2"))
        self.gridLayout.addWidget(self.delstar_2, 1, 3, 1, 1)
        self.gstar = QtGui.QLabel(Frame)
        self.gstar.setObjectName(_fromUtf8("gstar"))
        self.gridLayout.addWidget(self.gstar, 2, 2, 1, 1)
        self.z_reion = QtGui.QLineEdit(Frame)
        self.z_reion.setObjectName(_fromUtf8("z_reion"))
        self.gridLayout.addWidget(self.z_reion, 6, 1, 1, 1)
        self.hm = QtGui.QLabel(Frame)
        self.hm.setObjectName(_fromUtf8("hm"))
        self.gridLayout.addWidget(self.hm, 3, 0, 1, 1)
        self.metal_2 = QtGui.QLineEdit(Frame)
        self.metal_2.setObjectName(_fromUtf8("metal_2"))
        self.gridLayout.addWidget(self.metal_2, 2, 1, 1, 1)
        self.hm_2 = QtGui.QLineEdit(Frame)
        self.hm_2.setObjectName(_fromUtf8("hm_2"))
        self.gridLayout.addWidget(self.hm_2, 3, 1, 1, 1)
        self.J21_2 = QtGui.QLineEdit(Frame)
        self.J21_2.setObjectName(_fromUtf8("J21_2"))
        self.gridLayout.addWidget(self.J21_2, 4, 1, 1, 1)
        self.J21 = QtGui.QLabel(Frame)
        self.J21.setObjectName(_fromUtf8("J21"))
        self.gridLayout.addWidget(self.J21, 4, 0, 1, 1)
        self.a_spec = QtGui.QLineEdit(Frame)
        self.a_spec.setObjectName(_fromUtf8("a_spec"))
        self.gridLayout.addWidget(self.a_spec, 5, 1, 1, 1)
        self.z_ave_2 = QtGui.QLineEdit(Frame)
        self.z_ave_2.setObjectName(_fromUtf8("z_ave_2"))
        self.gridLayout.addWidget(self.z_ave_2, 7, 1, 1, 1)
        self.z_ave = QtGui.QLabel(Frame)
        self.z_ave.setObjectName(_fromUtf8("z_ave"))
        self.gridLayout.addWidget(self.z_ave, 7, 0, 1, 1)
        self.ndebris_2 = QtGui.QLineEdit(Frame)
        self.ndebris_2.setObjectName(_fromUtf8("ndebris_2"))
        self.gridLayout.addWidget(self.ndebris_2, 5, 3, 1, 1)
        self.ndebris = QtGui.QLabel(Frame)
        self.ndebris.setObjectName(_fromUtf8("ndebris"))
        self.gridLayout.addWidget(self.ndebris, 5, 2, 1, 1)
        self.f_ek = QtGui.QLabel(Frame)
        self.f_ek.setObjectName(_fromUtf8("f_ek"))
        self.gridLayout.addWidget(self.f_ek, 6, 2, 1, 1)
        self.f_ek_2 = QtGui.QLineEdit(Frame)
        self.f_ek_2.setObjectName(_fromUtf8("f_ek_2"))
        self.gridLayout.addWidget(self.f_ek_2, 6, 3, 1, 1)


        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        Frame.setWindowTitle(_translate("Frame", "Frame", None))
        self.a_reion.setText(_translate("Frame", "z_reion", None))
        self.isothermal.setText(_translate("Frame", "isothermal", None))
        self.aspec.setText(_translate("Frame", "a_spec", None))
        self.metal.setText(_translate("Frame", "metal", None))
        self.cooling.setText(_translate("Frame", "cooling", None))
        self.f_w.setText(_translate("Frame", "f_w=10.0, r_bubble=0", None))
        self.yld.setText(_translate("Frame", "eta_sn=0.0, yield=0.1", None))
        self.startime.setText(_translate("Frame", "t_star=0.0, eps_star", None))
        self.delstar.setText(_translate("Frame", "n_star=0.1, del_star=200", None))
        self.gstar.setText(_translate("Frame", "T2_star=0.0, g_star=1.6", None))
        self.hm.setText(_translate("Frame", "haardt_madau", None))
        self.J21.setText(_translate("Frame", "J21", None))
        self.z_ave.setText(_translate("Frame", "z_ave", None))
        self.ndebris.setText(_translate("Frame", "ndebris = 1", None))
        self.f_ek.setText(_translate("Frame", "f_ek = 1", None))

        self.Save.setStatusTip(_translate("Frame", "Save variables", None))
        self.Save.setText(_translate("Frame", "Save", None))
        self.Reset.setStatusTip(_translate("Frame", "Reset value", None))
        self.Reset.setText(_translate("Frame", "Reset", None))




    def close_application(self):
        sys.exit()



       

class AMR_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName(_fromUtf8("Frame"))
        Frame.resize(637, 206)
        Frame.setFrameShape(QtGui.QFrame.StyledPanel)
        Frame.setFrameShadow(QtGui.QFrame.Raised)

        self.Save = QtGui.QPushButton(Frame)
        self.Save.setGeometry(QtCore.QRect(0, 0, 85, 27))
        self.Save.setObjectName(_fromUtf8("Save"))
        self.Reset = QtGui.QPushButton(Frame)
        self.Reset.setGeometry(QtCore.QRect(90, 0, 85, 27))
        self.Reset.setObjectName(_fromUtf8("Reset"))

        self.gridLayout = QtGui.QGridLayout(Frame)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.levelmin = QtGui.QLabel(Frame)
        self.levelmin.setStatusTip(_fromUtf8(""))
        self.levelmin.setObjectName(_fromUtf8("levelmin"))
        self.gridLayout.addWidget(self.levelmin, 0, 0, 1, 1)
        self.editlevelmin = QtGui.QLineEdit(Frame)
        self.editlevelmin.setObjectName(_fromUtf8("editlevelmin"))
        self.gridLayout.addWidget(self.editlevelmin, 0, 1, 1, 1)
        self.hm = QtGui.QLabel(Frame)
        self.hm.setObjectName(_fromUtf8("hm"))
        self.gridLayout.addWidget(self.hm, 0, 2, 1, 1)
        self.editngridtot = QtGui.QLineEdit(Frame)
        self.editngridtot.setObjectName(_fromUtf8("editngridtot"))
        self.gridLayout.addWidget(self.editngridtot, 0, 3, 1, 1)
        self.levelmax = QtGui.QLabel(Frame)
        self.levelmax.setObjectName(_fromUtf8("levelmax"))
        self.gridLayout.addWidget(self.levelmax, 1, 0, 1, 1)
        self.editlevelmax = QtGui.QLineEdit(Frame)
        self.editlevelmax.setObjectName(_fromUtf8("editlevelmax"))
        self.gridLayout.addWidget(self.editlevelmax, 1, 1, 1, 1)
        self.npartmax = QtGui.QLabel(Frame)
        self.npartmax.setObjectName(_fromUtf8("npartmax"))
        self.gridLayout.addWidget(self.npartmax, 1, 2, 1, 1)
        self.editnpartmax = QtGui.QLineEdit(Frame)
        self.editnpartmax.setObjectName(_fromUtf8("editnpartmax"))
        self.gridLayout.addWidget(self.editnpartmax, 1, 3, 1, 1)
        self.ngridmax = QtGui.QLabel(Frame)
        self.ngridmax.setStatusTip(_fromUtf8(""))
        self.ngridmax.setObjectName(_fromUtf8("ngridmax"))
        self.gridLayout.addWidget(self.ngridmax, 2, 0, 1, 1)
        self.editngridmax = QtGui.QLineEdit(Frame)
        self.editngridmax.setObjectName(_fromUtf8("editngridmax"))
        self.gridLayout.addWidget(self.editngridmax, 2, 1, 1, 1)
        self.nparttot = QtGui.QLabel(Frame)
        self.nparttot.setObjectName(_fromUtf8("nparttot"))
        self.gridLayout.addWidget(self.nparttot, 2, 2, 1, 1)
        self.editnparttot = QtGui.QLineEdit(Frame)
        self.editnparttot.setObjectName(_fromUtf8("editnparttot"))
        self.gridLayout.addWidget(self.editnparttot, 2, 3, 1, 1)
        self.nexpand = QtGui.QLabel(Frame)
        self.nexpand.setObjectName(_fromUtf8("nexpand"))
        self.gridLayout.addWidget(self.nexpand, 3, 0, 1, 1)
        self.editnexpand = QtGui.QLineEdit(Frame)
        self.editnexpand.setObjectName(_fromUtf8("editnexpand"))
        self.gridLayout.addWidget(self.editnexpand, 3, 1, 1, 1)
        self.boxlen = QtGui.QLabel(Frame)
        self.boxlen.setObjectName(_fromUtf8("boxlen"))
        self.gridLayout.addWidget(self.boxlen, 3, 2, 1, 1)
        self.editboxlen = QtGui.QLineEdit(Frame)
        self.editboxlen.setObjectName(_fromUtf8("editboxlen"))
        self.gridLayout.addWidget(self.editboxlen, 3, 3, 1, 1)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        Frame.setWindowTitle(_translate("Frame", "Frame", None))
        self.levelmin.setText(_translate("Frame", "levelmin", None))
        self.editlevelmin.setStatusTip(_translate("Frame", "edit levelmax", None))
        self.hm.setText(_translate("Frame", "ngridtot", None))
        self.editngridtot.setStatusTip(_translate("Frame", "edit ngridtot", None))
        self.levelmax.setText(_translate("Frame", "levelmax", None))
        self.editlevelmax.setStatusTip(_translate("Frame", "edit levelmax", None))
        self.npartmax.setText(_translate("Frame", "npartmax", None))
        self.editnpartmax.setStatusTip(_translate("Frame", "edit npartmax", None))
        self.ngridmax.setText(_translate("Frame", "ngridmax", None))
        self.editngridmax.setStatusTip(_translate("Frame", "edit ngridmax", None))
        self.nparttot.setText(_translate("Frame", "nparttot", None))
        self.editnparttot.setStatusTip(_translate("Frame", "edit nparttot", None))
        self.nexpand.setText(_translate("Frame", "nexpand", None))
        self.editnexpand.setStatusTip(_translate("Frame", "edit nexpand", None))
        self.boxlen.setText(_translate("Frame", "boxlen", None))
        self.editboxlen.setStatusTip(_translate("Frame", "edit boxlen", None))

        self.Save.setStatusTip(_translate("Frame", "Save variables", None))
        self.Save.setText(_translate("Frame", "Save", None))
        self.Reset.setStatusTip(_translate("Frame", "Reset value", None))
        self.Reset.setText(_translate("Frame", "Reset", None))





class Init_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName(_fromUtf8("Frame"))
        Frame.resize(561, 571)
        Frame.setFrameShape(QtGui.QFrame.StyledPanel)
        Frame.setFrameShadow(QtGui.QFrame.Raised)

        self.Save = QtGui.QPushButton(Frame)
        self.Save.setGeometry(QtCore.QRect(0, 0, 85, 27))
        self.Save.setObjectName(_fromUtf8("Save"))
        self.Reset = QtGui.QPushButton(Frame)
        self.Reset.setGeometry(QtCore.QRect(90, 0, 85, 27))
        self.Reset.setObjectName(_fromUtf8("Reset"))


        self.gridLayout = QtGui.QGridLayout(Frame)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.nregion = QtGui.QLabel(Frame)
        self.nregion.setStatusTip(_fromUtf8(""))
        self.nregion.setObjectName(_fromUtf8("nregion"))
        self.gridLayout.addWidget(self.nregion, 0, 0, 1, 1)
        self.editnregion = QtGui.QLineEdit(Frame)
        self.editnregion.setObjectName(_fromUtf8("editnregion"))
        self.gridLayout.addWidget(self.editnregion, 0, 1, 1, 1)
        self.length_x = QtGui.QLabel(Frame)
        self.length_x.setObjectName(_fromUtf8("length_x"))
        self.gridLayout.addWidget(self.length_x, 0, 2, 1, 1)
        self.editlength_x = QtGui.QLineEdit(Frame)
        self.editlength_x.setObjectName(_fromUtf8("editlength_x"))
        self.gridLayout.addWidget(self.editlength_x, 0, 3, 1, 1)
        self.region_type = QtGui.QLabel(Frame)
        self.region_type.setObjectName(_fromUtf8("region_type"))
        self.gridLayout.addWidget(self.region_type, 1, 0, 1, 1)
        self.editregion_type = QtGui.QLineEdit(Frame)
        self.editregion_type.setObjectName(_fromUtf8("editregion_type"))
        self.gridLayout.addWidget(self.editregion_type, 1, 1, 1, 1)
        self.nparttot = QtGui.QLabel(Frame)
        self.nparttot.setObjectName(_fromUtf8("nparttot"))
        self.gridLayout.addWidget(self.nparttot, 1, 2, 1, 1)
        self.editlength_y = QtGui.QLineEdit(Frame)
        self.editlength_y.setObjectName(_fromUtf8("editlength_y"))
        self.gridLayout.addWidget(self.editlength_y, 1, 3, 1, 1)
        self.x_center = QtGui.QLabel(Frame)
        self.x_center.setStatusTip(_fromUtf8(""))
        self.x_center.setObjectName(_fromUtf8("x_center"))
        self.gridLayout.addWidget(self.x_center, 2, 0, 1, 1)
        self.editx_center = QtGui.QLineEdit(Frame)
        self.editx_center.setObjectName(_fromUtf8("editx_center"))
        self.gridLayout.addWidget(self.editx_center, 2, 1, 1, 1)
        self.length_z = QtGui.QLabel(Frame)
        self.length_z.setObjectName(_fromUtf8("length_z"))
        self.gridLayout.addWidget(self.length_z, 2, 2, 1, 1)
        self.editlength_z = QtGui.QLineEdit(Frame)
        self.editlength_z.setObjectName(_fromUtf8("editlength_z"))
        self.gridLayout.addWidget(self.editlength_z, 2, 3, 1, 1)
        self.y_center = QtGui.QLabel(Frame)
        self.y_center.setObjectName(_fromUtf8("y_center"))
        self.gridLayout.addWidget(self.y_center, 3, 0, 1, 1)
        self.edity_center = QtGui.QLineEdit(Frame)
        self.edity_center.setObjectName(_fromUtf8("edity_center"))
        self.gridLayout.addWidget(self.edity_center, 3, 1, 1, 1)
        self.exp_region = QtGui.QLabel(Frame)
        self.exp_region.setObjectName(_fromUtf8("exp_region"))
        self.gridLayout.addWidget(self.exp_region, 3, 2, 1, 1)
        self.editexp_region = QtGui.QLineEdit(Frame)
        self.editexp_region.setObjectName(_fromUtf8("editexp_region"))
        self.gridLayout.addWidget(self.editexp_region, 3, 3, 1, 1)
        self.z_center = QtGui.QLabel(Frame)
        self.z_center.setObjectName(_fromUtf8("z_center"))
        self.gridLayout.addWidget(self.z_center, 4, 0, 1, 1)
        self.editz_center = QtGui.QLineEdit(Frame)
        self.editz_center.setObjectName(_fromUtf8("editz_center"))
        self.gridLayout.addWidget(self.editz_center, 4, 1, 1, 1)
        self.p_region_2 = QtGui.QLabel(Frame)
        self.p_region_2.setObjectName(_fromUtf8("p_region_2"))
        self.gridLayout.addWidget(self.p_region_2, 4, 2, 1, 1)
        self.editfiletype = QtGui.QLineEdit(Frame)
        self.editfiletype.setObjectName(_fromUtf8("editfiletype"))
        self.gridLayout.addWidget(self.editfiletype, 4, 3, 1, 1)
        self.d_region = QtGui.QLabel(Frame)
        self.d_region.setObjectName(_fromUtf8("d_region"))
        self.gridLayout.addWidget(self.d_region, 5, 0, 1, 1)
        self.editd_region = QtGui.QLineEdit(Frame)
        self.editd_region.setObjectName(_fromUtf8("editd_region"))
        self.gridLayout.addWidget(self.editd_region, 5, 1, 1, 1)
        self.aexp_ini = QtGui.QLabel(Frame)
        self.aexp_ini.setObjectName(_fromUtf8("aexp_ini"))
        self.gridLayout.addWidget(self.aexp_ini, 5, 2, 1, 1)
        self.editaexp_ini = QtGui.QLineEdit(Frame)
        self.editaexp_ini.setObjectName(_fromUtf8("editaexp_ini"))
        self.gridLayout.addWidget(self.editaexp_ini, 5, 3, 1, 1)
        self.u_region = QtGui.QLabel(Frame)
        self.u_region.setObjectName(_fromUtf8("u_region"))
        self.gridLayout.addWidget(self.u_region, 6, 0, 1, 1)
        self.editu_region = QtGui.QLineEdit(Frame)
        self.editu_region.setObjectName(_fromUtf8("editu_region"))
        self.gridLayout.addWidget(self.editu_region, 6, 1, 1, 1)
        self.multiple = QtGui.QLabel(Frame)
        self.multiple.setObjectName(_fromUtf8("multiple"))
        self.gridLayout.addWidget(self.multiple, 6, 2, 1, 1)
        self.editmultiple = QtGui.QLineEdit(Frame)
        self.editmultiple.setObjectName(_fromUtf8("editmultiple"))
        self.gridLayout.addWidget(self.editmultiple, 6, 3, 1, 1)
        self.w_region = QtGui.QLabel(Frame)
        self.w_region.setObjectName(_fromUtf8("w_region"))
        self.gridLayout.addWidget(self.w_region, 7, 0, 1, 1)
        self.editw_region = QtGui.QLineEdit(Frame)
        self.editw_region.setObjectName(_fromUtf8("editw_region"))
        self.gridLayout.addWidget(self.editw_region, 7, 1, 1, 1)
        self.initfile = QtGui.QLabel(Frame)
        self.initfile.setObjectName(_fromUtf8("initfile"))
        self.gridLayout.addWidget(self.initfile, 7, 2, 1, 1)
        self.editinitfile = QtGui.QLineEdit(Frame)
        self.editinitfile.setObjectName(_fromUtf8("editinitfile"))
        self.gridLayout.addWidget(self.editinitfile, 7, 3, 1, 1)
        self.p_region = QtGui.QLabel(Frame)
        self.p_region.setObjectName(_fromUtf8("p_region"))
        self.gridLayout.addWidget(self.p_region, 8, 0, 1, 1)
        self.editp_region = QtGui.QLineEdit(Frame)
        self.editp_region.setObjectName(_fromUtf8("editp_region"))
        self.gridLayout.addWidget(self.editp_region, 8, 1, 1, 1)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        Frame.setWindowTitle(_translate("Frame", "Frame", None))
        self.nregion.setText(_translate("Frame", "nregion", None))
        self.editnregion.setStatusTip(_translate("Frame", "edit nregion", None))
        self.length_x.setText(_translate("Frame", "length_x", None))
        self.editlength_x.setStatusTip(_translate("Frame", "edit length_x", None))
        self.region_type.setText(_translate("Frame", "region_type", None))
        self.editregion_type.setStatusTip(_translate("Frame", "edit region_type", None))
        self.nparttot.setText(_translate("Frame", "length_y", None))
        self.editlength_y.setStatusTip(_translate("Frame", "edit length_y", None))
        self.x_center.setText(_translate("Frame", "x_center", None))
        self.editx_center.setStatusTip(_translate("Frame", "edit x_center", None))
        self.length_z.setText(_translate("Frame", "length_z", None))
        self.editlength_z.setStatusTip(_translate("Frame", "edit length_z", None))
        self.y_center.setText(_translate("Frame", "y_center", None))
        self.edity_center.setStatusTip(_translate("Frame", "edit y_center", None))
        self.exp_region.setText(_translate("Frame", "exp_region", None))
        self.editexp_region.setStatusTip(_translate("Frame", "edit exp_region", None))
        self.z_center.setText(_translate("Frame", "z_center", None))
        self.editz_center.setStatusTip(_translate("Frame", "edit z_center", None))
        self.p_region_2.setText(_translate("Frame", "filetype", None))
        self.editfiletype.setStatusTip(_translate("Frame", "edit filetype", None))
        self.d_region.setText(_translate("Frame", "d_region", None))
        self.editd_region.setStatusTip(_translate("Frame", "edit d_region", None))
        self.aexp_ini.setText(_translate("Frame", "aexp_ini", None))
        self.editaexp_ini.setStatusTip(_translate("Frame", "edit aexp_ini", None))
        self.u_region.setText(_translate("Frame", "u_region", None))
        self.editu_region.setStatusTip(_translate("Frame", "edit u_region", None))
        self.multiple.setText(_translate("Frame", "multiple", None))
        self.editmultiple.setStatusTip(_translate("Frame", "edit multiple", None))
        self.w_region.setText(_translate("Frame", "w_region", None))
        self.editw_region.setStatusTip(_translate("Frame", "edit w_region", None))
        self.initfile.setText(_translate("Frame", "initfile", None))
        self.editinitfile.setStatusTip(_translate("Frame", "edit initfile", None))
        self.p_region.setText(_translate("Frame", "p_region", None))
        self.editp_region.setStatusTip(_translate("Frame", "edit p_region", None))

        self.Save.setStatusTip(_translate("Frame", "Save variables", None))
        self.Save.setText(_translate("Frame", "Save", None))
        self.Reset.setStatusTip(_translate("Frame", "Reset value", None))
        self.Reset.setText(_translate("Frame", "Reset", None))






class Output_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName(_fromUtf8("Frame"))
        Frame.resize(625, 341)
        Frame.setFrameShape(QtGui.QFrame.StyledPanel)
        Frame.setFrameShadow(QtGui.QFrame.Raised)
        
        self.Save = QtGui.QPushButton(Frame)
        self.Save.setGeometry(QtCore.QRect(0, 0, 85, 27))
        self.Save.setObjectName(_fromUtf8("Save"))
        self.Reset = QtGui.QPushButton(Frame)
        self.Reset.setGeometry(QtCore.QRect(90, 0, 85, 27))
        self.Reset.setObjectName(_fromUtf8("Reset"))


        self.gridLayout = QtGui.QGridLayout(Frame)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tend = QtGui.QLabel(Frame)
        self.tend.setStatusTip(_fromUtf8(""))
        self.tend.setObjectName(_fromUtf8("tend"))
        self.gridLayout.addWidget(self.tend, 0, 0, 1, 1)
        self.edittend = QtGui.QLineEdit(Frame)
        self.edittend.setObjectName(_fromUtf8("edittend"))
        self.gridLayout.addWidget(self.edittend, 0, 1, 1, 1)
        self.noutput = QtGui.QLabel(Frame)
        self.noutput.setObjectName(_fromUtf8("noutput"))
        self.gridLayout.addWidget(self.noutput, 0, 2, 1, 1)
        self.editnoutput = QtGui.QLineEdit(Frame)
        self.editnoutput.setObjectName(_fromUtf8("editnoutput"))
        self.gridLayout.addWidget(self.editnoutput, 0, 3, 1, 1)
        self.delta_tout = QtGui.QLabel(Frame)
        self.delta_tout.setObjectName(_fromUtf8("delta_tout"))
        self.gridLayout.addWidget(self.delta_tout, 1, 0, 1, 1)
        self.editdelta_tout_2 = QtGui.QLineEdit(Frame)
        self.editdelta_tout_2.setObjectName(_fromUtf8("editdelta_tout_2"))
        self.gridLayout.addWidget(self.editdelta_tout_2, 1, 1, 1, 1)
        self.tout = QtGui.QLabel(Frame)
        self.tout.setObjectName(_fromUtf8("tout"))
        self.gridLayout.addWidget(self.tout, 1, 2, 1, 1)
        self.edittout = QtGui.QLineEdit(Frame)
        self.edittout.setObjectName(_fromUtf8("edittout"))
        self.gridLayout.addWidget(self.edittout, 1, 3, 1, 1)
        self.aend = QtGui.QLabel(Frame)
        self.aend.setStatusTip(_fromUtf8(""))
        self.aend.setObjectName(_fromUtf8("aend"))
        self.gridLayout.addWidget(self.aend, 2, 0, 1, 1)
        self.editaend = QtGui.QLineEdit(Frame)
        self.editaend.setObjectName(_fromUtf8("editaend"))
        self.gridLayout.addWidget(self.editaend, 2, 1, 1, 1)
        self.aout = QtGui.QLabel(Frame)
        self.aout.setObjectName(_fromUtf8("aout"))
        self.gridLayout.addWidget(self.aout, 2, 2, 1, 1)
        self.editaout = QtGui.QLineEdit(Frame)
        self.editaout.setObjectName(_fromUtf8("editaout"))
        self.gridLayout.addWidget(self.editaout, 2, 3, 1, 1)
        self.delta_tout_2 = QtGui.QLabel(Frame)
        self.delta_tout_2.setObjectName(_fromUtf8("delta_tout_2"))
        self.gridLayout.addWidget(self.delta_tout_2, 3, 0, 1, 1)
        self.editdelta_tout = QtGui.QLineEdit(Frame)
        self.editdelta_tout.setObjectName(_fromUtf8("editdelta_tout"))
        self.gridLayout.addWidget(self.editdelta_tout, 3, 1, 1, 1)
        self.foutput = QtGui.QLabel(Frame)
        self.foutput.setObjectName(_fromUtf8("foutput"))
        self.gridLayout.addWidget(self.foutput, 3, 2, 1, 1)
        self.editfoutput = QtGui.QLineEdit(Frame)
        self.editfoutput.setObjectName(_fromUtf8("editfoutput"))
        self.gridLayout.addWidget(self.editfoutput, 3, 3, 1, 1)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        Frame.setWindowTitle(_translate("Frame", "Frame", None))
        self.tend.setText(_translate("Frame", "tend", None))
        self.edittend.setStatusTip(_translate("Frame", "edit tend", None))
        self.noutput.setText(_translate("Frame", "noutput", None))
        self.editnoutput.setStatusTip(_translate("Frame", "edit noutput", None))
        self.delta_tout.setText(_translate("Frame", "delta_tout", None))
        self.editdelta_tout_2.setStatusTip(_translate("Frame", "edit delta_tout", None))
        self.tout.setText(_translate("Frame", "tout", None))
        self.edittout.setStatusTip(_translate("Frame", "edit tout", None))
        self.aend.setText(_translate("Frame", "aend", None))
        self.editaend.setStatusTip(_translate("Frame", "edit aend", None))
        self.aout.setText(_translate("Frame", "aout", None))
        self.editaout.setStatusTip(_translate("Frame", "edit aout", None))
        self.delta_tout_2.setText(_translate("Frame", "delta_tout", None))
        self.editdelta_tout.setStatusTip(_translate("Frame", "edit delta_tout", None))
        self.foutput.setText(_translate("Frame", "foutput", None))
        self.editfoutput.setStatusTip(_translate("Frame", "edit foutput", None))

        self.Save.setStatusTip(_translate("Frame", "Save variables", None))
        self.Save.setText(_translate("Frame", "Save", None))
        self.Reset.setStatusTip(_translate("Frame", "Reset value", None))
        self.Reset.setText(_translate("Frame", "Reset", None))






class Boundary_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName(_fromUtf8("Frame"))
        Frame.resize(625, 617)
        Frame.setFrameShape(QtGui.QFrame.StyledPanel)
        Frame.setFrameShadow(QtGui.QFrame.Raised)
        
        self.Save = QtGui.QPushButton(Frame)
        self.Save.setGeometry(QtCore.QRect(0, 0, 85, 27))
        self.Save.setObjectName(_fromUtf8("Save"))
        self.Reset = QtGui.QPushButton(Frame)
        self.Reset.setGeometry(QtCore.QRect(90, 0, 85, 27))
        self.Reset.setObjectName(_fromUtf8("Reset"))



        self.gridLayout = QtGui.QGridLayout(Frame)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.nboundary = QtGui.QLabel(Frame)
        self.nboundary.setStatusTip(_fromUtf8(""))
        self.nboundary.setObjectName(_fromUtf8("nboundary"))
        self.gridLayout.addWidget(self.nboundary, 0, 0, 1, 1)
        self.editnboundary = QtGui.QLineEdit(Frame)
        self.editnboundary.setObjectName(_fromUtf8("editnboundary"))
        self.gridLayout.addWidget(self.editnboundary, 0, 1, 1, 1)
        self.ibound_min = QtGui.QLabel(Frame)
        self.ibound_min.setObjectName(_fromUtf8("ibound_min"))
        self.gridLayout.addWidget(self.ibound_min, 0, 2, 1, 1)
        self.editibound_min = QtGui.QLineEdit(Frame)
        self.editibound_min.setObjectName(_fromUtf8("editibound_min"))
        self.gridLayout.addWidget(self.editibound_min, 0, 3, 1, 1)
        self.bound_type = QtGui.QLabel(Frame)
        self.bound_type.setObjectName(_fromUtf8("bound_type"))
        self.gridLayout.addWidget(self.bound_type, 1, 0, 1, 1)
        self.editbound_type = QtGui.QLineEdit(Frame)
        self.editbound_type.setObjectName(_fromUtf8("editbound_type"))
        self.gridLayout.addWidget(self.editbound_type, 1, 1, 1, 1)
        self.jbound_min = QtGui.QLabel(Frame)
        self.jbound_min.setObjectName(_fromUtf8("jbound_min"))
        self.gridLayout.addWidget(self.jbound_min, 1, 2, 1, 1)
        self.editjbound_min = QtGui.QLineEdit(Frame)
        self.editjbound_min.setObjectName(_fromUtf8("editjbound_min"))
        self.gridLayout.addWidget(self.editjbound_min, 1, 3, 1, 1)
        self.d_bound = QtGui.QLabel(Frame)
        self.d_bound.setStatusTip(_fromUtf8(""))
        self.d_bound.setObjectName(_fromUtf8("d_bound"))
        self.gridLayout.addWidget(self.d_bound, 2, 0, 1, 1)
        self.editd_bound = QtGui.QLineEdit(Frame)
        self.editd_bound.setObjectName(_fromUtf8("editd_bound"))
        self.gridLayout.addWidget(self.editd_bound, 2, 1, 1, 1)
        self.kbound_min = QtGui.QLabel(Frame)
        self.kbound_min.setObjectName(_fromUtf8("kbound_min"))
        self.gridLayout.addWidget(self.kbound_min, 2, 2, 1, 1)
        self.editkbound_min = QtGui.QLineEdit(Frame)
        self.editkbound_min.setObjectName(_fromUtf8("editkbound_min"))
        self.gridLayout.addWidget(self.editkbound_min, 2, 3, 1, 1)
        self.u_bound = QtGui.QLabel(Frame)
        self.u_bound.setObjectName(_fromUtf8("u_bound"))
        self.gridLayout.addWidget(self.u_bound, 3, 0, 1, 1)
        self.editu_bound = QtGui.QLineEdit(Frame)
        self.editu_bound.setObjectName(_fromUtf8("editu_bound"))
        self.gridLayout.addWidget(self.editu_bound, 3, 1, 1, 1)
        self.ibound_max = QtGui.QLabel(Frame)
        self.ibound_max.setObjectName(_fromUtf8("ibound_max"))
        self.gridLayout.addWidget(self.ibound_max, 3, 2, 1, 1)
        self.editibound_max = QtGui.QLineEdit(Frame)
        self.editibound_max.setObjectName(_fromUtf8("editibound_max"))
        self.gridLayout.addWidget(self.editibound_max, 3, 3, 1, 1)
        self.v_bound = QtGui.QLabel(Frame)
        self.v_bound.setObjectName(_fromUtf8("v_bound"))
        self.gridLayout.addWidget(self.v_bound, 4, 0, 1, 1)
        self.editv_bound = QtGui.QLineEdit(Frame)
        self.editv_bound.setObjectName(_fromUtf8("editv_bound"))
        self.gridLayout.addWidget(self.editv_bound, 4, 1, 1, 1)
        self.jbound_max = QtGui.QLabel(Frame)
        self.jbound_max.setObjectName(_fromUtf8("jbound_max"))
        self.gridLayout.addWidget(self.jbound_max, 4, 2, 1, 1)
        self.editjbound_max = QtGui.QLineEdit(Frame)
        self.editjbound_max.setObjectName(_fromUtf8("editjbound_max"))
        self.gridLayout.addWidget(self.editjbound_max, 4, 3, 1, 1)
        self.w_bound = QtGui.QLabel(Frame)
        self.w_bound.setObjectName(_fromUtf8("w_bound"))
        self.gridLayout.addWidget(self.w_bound, 5, 0, 1, 1)
        self.editw_bound = QtGui.QLineEdit(Frame)
        self.editw_bound.setObjectName(_fromUtf8("editw_bound"))
        self.gridLayout.addWidget(self.editw_bound, 5, 1, 1, 1)
        self.kbound_max = QtGui.QLabel(Frame)
        self.kbound_max.setObjectName(_fromUtf8("kbound_max"))
        self.gridLayout.addWidget(self.kbound_max, 5, 2, 1, 1)
        self.editkbound_max = QtGui.QLineEdit(Frame)
        self.editkbound_max.setObjectName(_fromUtf8("editkbound_max"))
        self.gridLayout.addWidget(self.editkbound_max, 5, 3, 1, 1)
        self.p_bound = QtGui.QLabel(Frame)
        self.p_bound.setObjectName(_fromUtf8("p_bound"))
        self.gridLayout.addWidget(self.p_bound, 6, 0, 1, 1)
        self.editp_bound = QtGui.QLineEdit(Frame)
        self.editp_bound.setObjectName(_fromUtf8("editp_bound"))
        self.gridLayout.addWidget(self.editp_bound, 6, 1, 1, 1)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        Frame.setWindowTitle(_translate("Frame", "Frame", None))
        self.nboundary.setText(_translate("Frame", "nboundary", None))
        self.editnboundary.setStatusTip(_translate("Frame", "edit nboundary", None))
        self.ibound_min.setText(_translate("Frame", "ibound_min", None))
        self.editibound_min.setStatusTip(_translate("Frame", "edit ibound_min", None))
        self.bound_type.setText(_translate("Frame", "bound_type", None))
        self.editbound_type.setStatusTip(_translate("Frame", "edit bound_type", None))
        self.jbound_min.setText(_translate("Frame", "jbound_min", None))
        self.editjbound_min.setStatusTip(_translate("Frame", "edit jbound_min", None))
        self.d_bound.setText(_translate("Frame", "d_bound", None))
        self.editd_bound.setStatusTip(_translate("Frame", "edit d_bound", None))
        self.kbound_min.setText(_translate("Frame", "kbound_min", None))
        self.editkbound_min.setStatusTip(_translate("Frame", "edit kbound_min", None))
        self.u_bound.setText(_translate("Frame", "u_bound", None))
        self.editu_bound.setStatusTip(_translate("Frame", "edit u_bound", None))
        self.ibound_max.setText(_translate("Frame", "ibound_max", None))
        self.editibound_max.setStatusTip(_translate("Frame", "edit ibound_max", None))
        self.v_bound.setText(_translate("Frame", "v_bound", None))
        self.editv_bound.setStatusTip(_translate("Frame", "edit v_bound", None))
        self.jbound_max.setText(_translate("Frame", "jbound_max", None))
        self.editjbound_max.setStatusTip(_translate("Frame", "edit jbound_max", None))
        self.w_bound.setText(_translate("Frame", "w_bound", None))
        self.editw_bound.setStatusTip(_translate("Frame", "edit w_bound", None))
        self.kbound_max.setText(_translate("Frame", "kbound_max", None))
        self.editkbound_max.setStatusTip(_translate("Frame", "edit kbound_max", None))
        self.p_bound.setText(_translate("Frame", "p_bound", None))
        self.editp_bound.setStatusTip(_translate("Frame", "edit p_bound", None))

        self.Save.setStatusTip(_translate("Frame", "Save variables", None))
        self.Save.setText(_translate("Frame", "Save", None))
        self.Reset.setStatusTip(_translate("Frame", "Reset value", None))
        self.Reset.setText(_translate("Frame", "Reset", None))




