# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'something.ui'
#
# Created: Thu Nov 17 15:32:01 2016
#      by: PyQt4 UI code generator 4.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_cosmo(object):
    def setupUi(self, cosmo):
        cosmo.setObjectName(_fromUtf8("cosmo"))
        cosmo.resize(833, 559)
        cosmo.setFrameShape(QtGui.QFrame.StyledPanel)
        cosmo.setFrameShadow(QtGui.QFrame.Raised)
        self.gridLayout = QtGui.QGridLayout(cosmo)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.cooling = QtGui.QLabel(cosmo)
        self.cooling.setStatusTip(_fromUtf8(""))
        self.cooling.setObjectName(_fromUtf8("cooling"))
        self.gridLayout.addWidget(self.cooling, 0, 0, 1, 1)
        self.editcooling = QtGui.QLineEdit(cosmo)
        self.editcooling.setObjectName(_fromUtf8("editcooling"))
        self.gridLayout.addWidget(self.editcooling, 0, 1, 1, 1)
        self.a_spec = QtGui.QLabel(cosmo)
        self.a_spec.setObjectName(_fromUtf8("a_spec"))
        self.gridLayout.addWidget(self.a_spec, 0, 2, 1, 1)
        self.edita_spec = QtGui.QLineEdit(cosmo)
        self.edita_spec.setObjectName(_fromUtf8("edita_spec"))
        self.gridLayout.addWidget(self.edita_spec, 0, 3, 1, 1)
        self.n_star = QtGui.QLabel(cosmo)
        self.n_star.setObjectName(_fromUtf8("n_star"))
        self.gridLayout.addWidget(self.n_star, 0, 4, 1, 1)
        self.editn_star = QtGui.QLineEdit(cosmo)
        self.editn_star.setObjectName(_fromUtf8("editn_star"))
        self.gridLayout.addWidget(self.editn_star, 0, 5, 1, 1)
        self.isothermal = QtGui.QLabel(cosmo)
        self.isothermal.setObjectName(_fromUtf8("isothermal"))
        self.gridLayout.addWidget(self.isothermal, 1, 0, 1, 1)
        self.editisothermal = QtGui.QLineEdit(cosmo)
        self.editisothermal.setObjectName(_fromUtf8("editisothermal"))
        self.gridLayout.addWidget(self.editisothermal, 1, 1, 1, 1)
        self.z_reion = QtGui.QLabel(cosmo)
        self.z_reion.setObjectName(_fromUtf8("z_reion"))
        self.gridLayout.addWidget(self.z_reion, 1, 2, 1, 1)
        self.editreion = QtGui.QLineEdit(cosmo)
        self.editreion.setObjectName(_fromUtf8("editreion"))
        self.gridLayout.addWidget(self.editreion, 1, 3, 1, 1)
        self.del_star = QtGui.QLabel(cosmo)
        self.del_star.setObjectName(_fromUtf8("del_star"))
        self.gridLayout.addWidget(self.del_star, 1, 4, 1, 1)
        self.editdel_star = QtGui.QLineEdit(cosmo)
        self.editdel_star.setObjectName(_fromUtf8("editdel_star"))
        self.gridLayout.addWidget(self.editdel_star, 1, 5, 1, 1)
        self.metal = QtGui.QLabel(cosmo)
        self.metal.setStatusTip(_fromUtf8(""))
        self.metal.setObjectName(_fromUtf8("metal"))
        self.gridLayout.addWidget(self.metal, 2, 0, 1, 1)
        self.editmetal = QtGui.QLineEdit(cosmo)
        self.editmetal.setObjectName(_fromUtf8("editmetal"))
        self.gridLayout.addWidget(self.editmetal, 2, 1, 1, 1)
        self.z_ave = QtGui.QLabel(cosmo)
        self.z_ave.setObjectName(_fromUtf8("z_ave"))
        self.gridLayout.addWidget(self.z_ave, 2, 2, 1, 1)
        self.editz_ave = QtGui.QLineEdit(cosmo)
        self.editz_ave.setObjectName(_fromUtf8("editz_ave"))
        self.gridLayout.addWidget(self.editz_ave, 2, 3, 1, 1)
        self.T2_star = QtGui.QLabel(cosmo)
        self.T2_star.setObjectName(_fromUtf8("T2_star"))
        self.gridLayout.addWidget(self.T2_star, 2, 4, 1, 1)
        self.editT2_star = QtGui.QLineEdit(cosmo)
        self.editT2_star.setObjectName(_fromUtf8("editT2_star"))
        self.gridLayout.addWidget(self.editT2_star, 2, 5, 1, 1)
        self.haardt_madau = QtGui.QLabel(cosmo)
        self.haardt_madau.setObjectName(_fromUtf8("haardt_madau"))
        self.gridLayout.addWidget(self.haardt_madau, 3, 0, 1, 1)
        self.edithaardt_madau = QtGui.QLineEdit(cosmo)
        self.edithaardt_madau.setObjectName(_fromUtf8("edithaardt_madau"))
        self.gridLayout.addWidget(self.edithaardt_madau, 3, 1, 1, 1)
        self.t_star = QtGui.QLabel(cosmo)
        self.t_star.setObjectName(_fromUtf8("t_star"))
        self.gridLayout.addWidget(self.t_star, 3, 2, 1, 1)
        self.editt_star = QtGui.QLineEdit(cosmo)
        self.editt_star.setObjectName(_fromUtf8("editt_star"))
        self.gridLayout.addWidget(self.editt_star, 3, 3, 1, 1)
        self.g_star = QtGui.QLabel(cosmo)
        self.g_star.setObjectName(_fromUtf8("g_star"))
        self.gridLayout.addWidget(self.g_star, 3, 4, 1, 1)
        self.editg_star = QtGui.QLineEdit(cosmo)
        self.editg_star.setObjectName(_fromUtf8("editg_star"))
        self.gridLayout.addWidget(self.editg_star, 3, 5, 1, 1)
        self.J21 = QtGui.QLabel(cosmo)
        self.J21.setObjectName(_fromUtf8("J21"))
        self.gridLayout.addWidget(self.J21, 4, 0, 1, 1)
        self.editJ21 = QtGui.QLineEdit(cosmo)
        self.editJ21.setObjectName(_fromUtf8("editJ21"))
        self.gridLayout.addWidget(self.editJ21, 4, 1, 1, 1)
        self.eps_star = QtGui.QLabel(cosmo)
        self.eps_star.setObjectName(_fromUtf8("eps_star"))
        self.gridLayout.addWidget(self.eps_star, 4, 2, 1, 1)
        self.editeps_star = QtGui.QLineEdit(cosmo)
        self.editeps_star.setObjectName(_fromUtf8("editeps_star"))
        self.gridLayout.addWidget(self.editeps_star, 4, 3, 1, 1)
        self.eta_sn = QtGui.QLabel(cosmo)
        self.eta_sn.setObjectName(_fromUtf8("eta_sn"))
        self.gridLayout.addWidget(self.eta_sn, 4, 4, 1, 1)
        self.editeta_sn = QtGui.QLineEdit(cosmo)
        self.editeta_sn.setObjectName(_fromUtf8("editeta_sn"))
        self.gridLayout.addWidget(self.editeta_sn, 4, 5, 1, 1)
        self.ndebris = QtGui.QLabel(cosmo)
        self.ndebris.setObjectName(_fromUtf8("ndebris"))
        self.gridLayout.addWidget(self.ndebris, 5, 0, 1, 1)
        self.editndebris = QtGui.QLineEdit(cosmo)
        self.editndebris.setObjectName(_fromUtf8("editndebris"))
        self.gridLayout.addWidget(self.editndebris, 5, 1, 1, 1)
        self.f_w = QtGui.QLabel(cosmo)
        self.f_w.setObjectName(_fromUtf8("f_w"))
        self.gridLayout.addWidget(self.f_w, 5, 2, 1, 1)
        self.editf_w = QtGui.QLineEdit(cosmo)
        self.editf_w.setObjectName(_fromUtf8("editf_w"))
        self.gridLayout.addWidget(self.editf_w, 5, 3, 1, 1)
        self.yield = QtGui.QLabel(cosmo)
        self.yield.setObjectName(_fromUtf8("yield"))
        self.gridLayout.addWidget(self.yield, 5, 4, 1, 1)
        self.edityield = QtGui.QLineEdit(cosmo)
        self.edityield.setObjectName(_fromUtf8("edityield"))
        self.gridLayout.addWidget(self.edityield, 5, 5, 1, 1)
        self.label_4 = QtGui.QLabel(cosmo)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 6, 0, 1, 1)
        self.editf_ek = QtGui.QLineEdit(cosmo)
        self.editf_ek.setObjectName(_fromUtf8("editf_ek"))
        self.gridLayout.addWidget(self.editf_ek, 6, 1, 1, 1)
        self.r_bubble = QtGui.QLabel(cosmo)
        self.r_bubble.setStatusTip(_fromUtf8(""))
        self.r_bubble.setObjectName(_fromUtf8("r_bubble"))
        self.gridLayout.addWidget(self.r_bubble, 6, 2, 1, 1)
        self.editr_bubble = QtGui.QLineEdit(cosmo)
        self.editr_bubble.setObjectName(_fromUtf8("editr_bubble"))
        self.gridLayout.addWidget(self.editr_bubble, 6, 3, 1, 1)

        self.retranslateUi(cosmo)
        QtCore.QMetaObject.connectSlotsByName(cosmo)

    def retranslateUi(self, cosmo):
        cosmo.setWindowTitle(_translate("cosmo", "Frame", None))
        self.cooling.setText(_translate("cosmo", "cooling", None))
        self.editcooling.setStatusTip(_translate("cosmo", "edit cooling", None))
        self.a_spec.setText(_translate("cosmo", "a_spec", None))
        self.edita_spec.setStatusTip(_translate("cosmo", "edit a_spec", None))
        self.n_star.setText(_translate("cosmo", "n_star", None))
        self.editn_star.setStatusTip(_translate("cosmo", "edit n_star", None))
        self.isothermal.setText(_translate("cosmo", "isothermal", None))
        self.editisothermal.setStatusTip(_translate("cosmo", "edit isothermal", None))
        self.z_reion.setText(_translate("cosmo", "z_reion", None))
        self.editreion.setStatusTip(_translate("cosmo", "edit reion", None))
        self.del_star.setText(_translate("cosmo", "del_star", None))
        self.editdel_star.setStatusTip(_translate("cosmo", "edit del_star", None))
        self.metal.setText(_translate("cosmo", "metal", None))
        self.editmetal.setStatusTip(_translate("cosmo", "edit metal", None))
        self.z_ave.setText(_translate("cosmo", "z_ave", None))
        self.editz_ave.setStatusTip(_translate("cosmo", "edit z_ave", None))
        self.T2_star.setText(_translate("cosmo", "T2_star", None))
        self.editT2_star.setStatusTip(_translate("cosmo", "edit T2_star", None))
        self.haardt_madau.setText(_translate("cosmo", "haardt_madau", None))
        self.edithaardt_madau.setStatusTip(_translate("cosmo", "edit haardt_madau", None))
        self.t_star.setText(_translate("cosmo", "t_star ", None))
        self.editt_star.setStatusTip(_translate("cosmo", "edit t_star", None))
        self.g_star.setText(_translate("cosmo", "g_star", None))
        self.editg_star.setStatusTip(_translate("cosmo", "edit g_star", None))
        self.J21.setText(_translate("cosmo", "J21", None))
        self.editJ21.setStatusTip(_translate("cosmo", "edit J21", None))
        self.eps_star.setText(_translate("cosmo", "eps_star", None))
        self.editeps_star.setStatusTip(_translate("cosmo", "edit eps_star", None))
        self.eta_sn.setText(_translate("cosmo", "eta_sn", None))
        self.editeta_sn.setStatusTip(_translate("cosmo", "edit eta_sn", None))
        self.ndebris.setText(_translate("cosmo", "ndebris", None))
        self.editndebris.setStatusTip(_translate("cosmo", "edit ndebris", None))
        self.f_w.setText(_translate("cosmo", "f_w", None))
        self.editf_w.setStatusTip(_translate("cosmo", "edit f_w", None))
        self.yield.setText(_translate("cosmo", "yield", None))
        self.edityield.setStatusTip(_translate("cosmo", "edit yield", None))
        self.label_4.setText(_translate("cosmo", "f_ek\n"
"", None))
        self.editf_ek.setStatusTip(_translate("cosmo", "edit f_ek", None))
        self.r_bubble.setText(_translate("cosmo", "r_bubble", None))
        self.editr_bubble.setStatusTip(_translate("cosmo", "edit r_bubble", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    cosmo = QtGui.QFrame()
    ui = Ui_cosmo()
    ui.setupUi(cosmo)
    cosmo.show()
    sys.exit(app.exec_())

